### PR TITLE
tests/integration: ensure the CI gives more time to some slow targets

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1625
Depends-On: https://github.com/ansible-collections/community.aws/pull/1468
Depends-On: https://github.com/ansible-collections/community.aws/pull/1473

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Review by tremble — COMMENTED** [review]
Do you think it's worth using
`#time=7m` rather than `time=7m` (which could be interpreted as the name of a group)

**Comment by goneri** [comment]
> Do you think it's worth using `#time=7m` rather than `time=7m` (which could be interpreted as the name of a group)

I would prefer to stay like this. For most of us, `#time=7m` looks like a disabled line.

This being said, we can also use a different file to store this information.

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
@goneri - I think in the medium term we need a proper metadata format rather than (ab)using the groups file.  But let's at least get this working

**Comment by goneri** [comment]
regate

**Pull request merged**
