### PR TITLE
SSM connection - set S3 addressing style

### LINKED ISSUE #705: Connection Issues with "aws_ssm.py" when S3 bucket is newly created
### Summary

When i create a S3 Bucket via terraform and then run ansible via AWS SSM i get error's from the ansible playbook cause SSM connection moduel uses the Global S3 Bucket DNS Name which DNS propagation will take up to 24h. The boto3 client doesn't follow the redirection, instead the redirection  breaks the ansible playbook.

### Issue Type

Bug Report

### Component Name

aws_ssm.py (AWS Session manager Connection module)

### Ansible Version

```console (paste below)
ansible 2.9.24
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jkritzen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
```

### Collection Versions

```console (paste below)


```

### AWS SDK versions

```console (paste below)
ame: boto3
Version: 1.17.112
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /home/jkritzen/.local/lib/python3.9/site-packages
Requires: jmespath, botocore, s3transfer
Required-by: cloudsplaining, checkov, aws-sam-translator
---
Name: botocore
Version: 1.21.35
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /home/jkritzen/.local/lib/python3.9/site-packages
Requires: urllib3, python-dateutil, jmespath
Required-by: s3transfer, cloudsplaining, boto3, awscli
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Centos 7+8, Fedora 33, Amazon Linux 2 (Issue is Independent from OS)

### Steps to Reproduce

1) Create a S3 bucket for usage with ansible aws collection
2) Run ansible playbook with fresh S3 bucket
 

```yaml (paste below)
name: check the basics - linux
  hosts: all
  gather_facts: False
  tags: smoke

  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_region: eu-central-1
    ansible_aws_ssm_bucket_name: "Your Bucket Name"
    content: 'Some test content'
    test_filename: 'test.txt'
    remote_file: "/tmp/{{ test_filename }}"
    local_file: "/tmp/{{ inventory_hostname }}.txt"
  tasks:
  - name: ping
    ping:
    tags: ping
  - name: facts
    setup:
    tags: facts
  - name: command
    command: 'uname -a'
    changed_when: False
    tags: command
```
Which results in:
```
TASK [ping] ************************************************************************************
fatal: [i-056d93f5ac0e2e73e]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/u
sr/bin/python"}, "changed": false, "module_stderr": "", "module_stdout": "  File \"/home/ssm-use
r/.ansible/tmp/ansible-tmp-1630996611.7029357-2571004-39322398271826/AnsiballZ_ping.py\", line 1
\r\r\n    <?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\r\n    ^\r\r\nSyntaxError: invalid syntax
\r\r", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Expected Results

The "aws_ssm.py" connection module uses a not recommended config wich causes a "HTTP 307 Temporary Redirect response" from the S3 URL:

More infos:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingRouting.html#TemporaryRedirection
https://aws.amazon.com/de/premiumsupport/knowledge-center/s3-http-307-response/

To avoid the 307 Temporary Redirect response, send requests only to the Regional endpoint in the same Region as your S3 bucket: https://boto3.amazonaws.com/v1/documentation/api/1.9.42/guide/s3.html

In general, the SDK will handle the decision of what style to use for you, but there are some cases where you may want to set it yourself. For instance, if you have a CORS configured bucket that is only a few hours old, you may need to use path style addressing for generating pre-signed POSTs and URLs until the necessary DNS changes have time to propagate.

Within the ssm connection module (aws_ssm.py) it can be fixed using the "path" adressing style by changing:

```
        client = session.client(
            service,
            config=Config(signature_version="s3v4")
        )
        return client
```
 to 
```
        client = session.client(
            service,
            config=Config(signature_version="s3v4",s3={'addressing_style': 'path'})
        )
        return client
```

### Actual Results

With current aws_ssm.py:

```console (paste below)
<i-056d93f5ac0e2e73e> EXEC curl 'https://s3-777-test-advanced-ssm.s3.amazonaws.
com/i-056d93f5ac0e2e73e//home/ssm-user/.ansible/tmp/ansible-tmp-1630996682.7521243-2571157-41384
86885801/AnsiballZ_ping.py
fatal: [i-056d93f5ac0e2e73e]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "",
    "module_stdout": "  File \"/home/ssm-user/.ansible/tmp/ansible-tmp-1630996871.0271783-2571514-241697094330155/AnsiballZ_ping.py\", line 1\r\r\n    <?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\r\n    ^\r\r\nSyntaxError: invalid syntax\r\r",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

With config style "path":

```
TASK [ping] *******************************************************************************************************************************************************************************************************************************************
<i-056d93f5ac0e2e73e> EXEC curl 'https://s3.eu-central-1.amazonaws.com/s3-777-test-advanced-ssm/i-056d93f5ac0e2e73e//home/ssm-user/.ansible/tmp/ansible-tmp-1630996924.4223547-2571701-237546745523938/AnsiballZ_ping.py?
ok: [i-056d93f5ac0e2e73e] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    },
    "ping": "pong"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by jfhovinne**
##### SUMMARY

Fixes #705 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

aws_ssm

##### ADDITIONAL INFORMATION

I confirm the connection issue described in #705 (I got the redirect error multiple times with different accounts + new buckets), which is fixed by applying the proposed patch, i.e. using the 'path' addressing style.

### CODE REVIEW

**Comment by 116davinder** [comment]
@jfhovinne, you would need to write doc fragment + test case if possible.
example: https://github.com/ansible-collections/community.aws/blob/main/changelogs/fragments/499-elb-module-add-ip_address_type_option.yml

The integration test case will be great.

**Comment by jfhovinne** [comment]
After investigation, I see that simply setting the addressing style fixes the issue, so we can use `virtual` instead.

**Comment by 116davinder** [comment]
> After investigation, I see that simply setting the addressing style fixes the issue, so we can use `virtual` instead.

Can you try with `auto` option instead of `virtual`?
```
addressing_style: The S3 addressing style. When necessary, Boto automatically switches the addressing style to an appropriate value. The following values are supported.

auto
(Default) Attempts to use virtual, but falls back to path if necessary.

path
Bucket name is included in the URI path.

virtual
Bucket name is included in the hostname.
```
ref: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-a-configuration-file

I believe, the best option is to take an extra parameter for it and `auto` as the default option.

@tremble / @markuman / @jillr , any suggestions for this issue?

**Comment by jfhovinne** [comment]
@116davinder The connection issue still occurs when setting the addressing style to `auto`.
Also I was suggesting `virtual` instead of `path` because `path` may be deprecated by AWS in the future.

**Comment by jfhovinne** [comment]
@116davinder Anything else blocking that PR?

**Comment by gillg** [comment]
duplicate of https://github.com/ansible-collections/community.aws/pull/786 and definitely not generic. #786 is preferable.
Could be closed

**Comment by jfhovinne** [comment]
The problem is that the issue is not fixed with #786 and default settings.

**Comment by tremble** [comment]
Thanks for taking the time to open this PR.

#1633 has now been merged which should add this functionality to release 5.2.0 of this collection

**Pull request closed without merging**
