### PR TITLE
Fix module documentation schema errors

### LINKED ISSUE #79: Some documentation errors in the cloudwatchlogs_log_group_metric_filter and ecs_service modules
##### SUMMARY

I've written a schema for DOCUMENTATION, RETURN, etc.  There are a few problems in the structure of the return docs on a pair of modules:
```
E   module -> community.aws.cloudwatchlogs_log_group_metric_filter -> return -> metric_filters -> contains -> creation_time
E     none is not an allowed value (type=type_error.none.not_allowed)
E   module -> community.aws.cloudwatchlogs_log_group_metric_filter -> return -> metric_filters -> contains -> filter_name
E     none is not an allowed value (type=type_error.none.not_allowed)
E   module -> community.aws.cloudwatchlogs_log_group_metric_filter -> return -> metric_filters -> contains -> filter_pattern
E     none is not an allowed value (type=type_error.none.not_allowed)
E   module -> community.aws.cloudwatchlogs_log_group_metric_filter -> return -> metric_filters -> contains -> log_group_name
E     none is not an allowed value (type=type_error.none.not_allowed)
E   module -> community.aws.cloudwatchlogs_log_group_metric_filter -> return -> metric_filters -> contains -> metric_filter_count
E     none is not an allowed value (type=type_error.none.not_allowed)
E   module -> community.aws.ecs_service -> doc -> options -> placement_constraints -> suboptions
E     none is not an allowed value (type=type_error.none.not_allowed)
```

Since this schema is new, it is possible that None should be allowed in one or all of the locations listed.  If so, let me know and we can discuss whether/how to update the schema to allow that.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
* cloudwatchlogs_log_group_metric_filter.py
* ecs_service.py

##### ANSIBLE VERSION

```paste below

```

### PR DESCRIPTION
**Pull request by jillr**
##### SUMMARY ##### 
`ecs_service` is missing suboptions data for `placement_constraints`
Return docs for `cloudwatchlogs_log_group_metric_filter` are missing suboption descriptions and are just plain wrong. Correct type and values.

Fixes #79

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
ecs_service
cloudwatchlogs_log_group_metric_filter

### CODE REVIEW

**Comment by abadger** [comment]
Checked it with my docs schema and it now passes.  +1 from me :-)

**Comment by jillr** [comment]
@tremble Turns out the ecs_service return docs have never been correct.  Any concerns with this pr?

**Comment by jillr** [comment]
@tremble Good call, fixed - also thanks for knowing what I meant since `cloudwatchlogs_log_group_metric_filter` had the incorrect return docs, not `ecs_service`. :)

**Comment by tremble** [comment]
LGTM

**Pull request merged**
