### PR TITLE
redshift_info - fix invalid import path for botocore exceptions

### LINKED ISSUE #968: Invalid import path for BotoCoreError in redshift_info module
### Summary

In case of any AWS related error (like missing permissions) the module will throw a gigantic python stack trace with error summary as:
```
line 304, in find_clusters
NameError: name 'BotoCoreError' is not defined
```
This is due to an invalid import path that is present in the module https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/redshift_info.py#L280
Instead of `from botocore.exception` it should be `from botocore.exceptions`. Once that is done, ansible no longer hides the real error with the stack trace.

### Issue Type

Bug Report

### Component Name

redshift_info

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/wojtek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

### Collection Versions

Non-relevant

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /home/wojtek/.local/lib/python3.6/site-packages
Requires:
---
Name: boto3
Version: 1.20.54
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /home/wojtek/.local/lib/python3.6/site-packages
Requires: jmespath, s3transfer, botocore
---
Name: botocore
Version: 1.23.54
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /home/wojtek/.local/lib/python3.6/site-packages
Requires: jmespath, urllib3, python-dateutil
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

Run the module without DescribeClusters permission.

### Expected Results

AWS API error on missing permissions is shown.

### Actual Results

Python stack trace ending with
```
line 304, in find_clusters
NameError: name 'BotoCoreError' is not defined
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by winglot**
Depends-On: https://github.com/ansible-collections/community.aws/pull/979

##### SUMMARY

 - Fix invalid import path for botocore exceptions
 - Fixes #968 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
redshift_info

### CODE REVIEW

**Review by marknet15 — APPROVED** [review]

**Comment by marknet15** [comment]
@winglot the fix looks good 👍🏻 but can you add a changelog fragment ?
https://github.com/ansible-collections/community.aws/blob/main/CONTRIBUTING.md#changelog-fragment

**Comment by winglot** [comment]
@marknet15 done

**Comment by marknet15** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]
@winglot Thank you.

**Pull request merged**
