### PR TITLE
ec2_launch_template - scrub None parameters from what we'll pass to create_launch_config

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Because we now define suboptions for network configuration we need to make sure that when some of them are None we remove them.

Depends on: https://github.com/ansible-collections/amazon.aws/pull/262

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_launch_template

##### ADDITIONAL INFORMATION

todo:
- [x] changelog
- [x] integration tests

### CODE REVIEW

**Comment by stefanhorning** [comment]
didn't work for me. While https://github.com/ansible-collections/community.aws/pull/438 does.

**Comment by felixfontein** [comment]
@stefanhorning did you test it together with https://github.com/ansible-collections/amazon.aws/pull/262, or did you just test this PR individually? (If the latter, it is not surprising at all that it didn't work.)

**Comment by stefanhorning** [comment]
Ah, no I missed that. Sorry.

**Review by felixfontein — APPROVED** [review]

**Comment by tremble** [comment]
Has tests (which fail prior to the change) and a peer review.  Merging

**Pull request merged**
