### PR TITLE
Don't notify willthames for AWS modules

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY
Don't notify willthames for AWS modules

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
botmeta

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by willthames** [comment]
I'm not keeping up with Ansible for AWS so this just reflects reality

**Comment by tremble** [comment]
Thanks for your work over the years @willthames

**Comment by willthames** [comment]
thanks @tremble - very kind of you to say

**Comment by Akasurde** [comment]
@willthames Thanks for working on AWS modules. I really appreciate the work you did.

**Comment by willthames** [comment]
thanks @Akasurde, it was a pleasure working with you

**Pull request merged**
