### PR TITLE
ssm connection plugin - Replace Fedora tests with CentOS 9

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Applies black to the SSM connection plugin
Fedora 34 AMIs aren't available for integration tests any more, move over to CentOS 9 because Fedora Images will keep going away.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

aws_ssm

### CODE REVIEW

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Review by markuman — APPROVED** [review]

**Comment by alinabuzachis** [comment]
regate

**Comment by tremble** [comment]
recheck

**Pull request merged**
