### PR TITLE
Added support for 'vpc_endpoint_type'.

### PR DESCRIPTION
**Pull request by Proksima**
##### SUMMARY
Add 'vpc_endpoint_type' support to 'ec2_vpc_endpoint'.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ec2_vpc_endpoint

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by Proksima** [comment]
Hmm, what is the procedure to get coverage? Should I write a test? I see no existing test for this module...

**Review by tremble — CHANGES_REQUESTED** [review]
Thanks for taking the time to raise this PR.

Generally looks good.  I've just one small request: please add a changelog entry:  https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

**Comment by Proksima** [comment]
Added changelog as requested!

**Review by tremble — APPROVED** [review]
LGTM

**Pull request merged**
