### PR TITLE
Add integration tests for redshift_subnet_group

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Add integration tests for redshift_subnet_group

- [ ] CI / IAM Permissions

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

redshift_subnet_group

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
These tests are currently part of #724 and have been reviewed there.  I'm going to merge them just so they can exist as a separate commit, and we can gate 724 once 2.0.0 is out the door.

**Pull request merged**
