### PR TITLE
Cleanup ec2_elb*

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

This effectively reverts https://github.com/ansible/ansible/pull/30532

@wimnat originally tried to keep ec2_elb, ec2_elb_lb and their fact/info partners separate from elb_instance / elb_classic_lb so that when a boto3 migration was performed the API/return values could be changed.  We no longer have a 'preview' flag on the interface, so this is just causing duplication.

- ec2_elb_info now has a boto3 based equivalent elb_classic_lb_info deprecate it so we can drop the old boto based module
- elb_classic_lb was never rewritten, point it at amazon.aws.ec2_elb_lb so we only try and do the boto3 migration in one place
- elb_instance was never rewritten, point ec2_elb at community.aws.elb_instance so we only try and do the boto3 migration in one place

Before we release 2.0.0 let's get this back to something vaguely consistent.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_elb
ec2_elb_lb
ec2_elb_info
elb_classic_lb
elb_classic_lb_info

### CODE REVIEW

**Comment by jillr** [comment]
This issue helped me understand the history so leaving it here for anyone else who comes across this PR:
https://github.com/ansible/ansible/issues/30494

Thanks for untangling this @tremble

**Review by jillr — COMMENTED** [review]
It would be good to have a changelog explaining that there was code duplication and that's why we already removed the file even though the redirect says it won't go away until 3.0. Folks might go looking for the module on-disk if they're debugging something.

**Review by jillr — APPROVED** [review]

**Comment by jillr** [comment]
@tremble I'm +1 to gate this once the merge conflicts are resolved, thanks!

**Review by markuman — APPROVED** [review]
LGTM

**Pull request merged**
