### PR TITLE
New modules: Transit Gateway VPC attachments

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Adds support for EC2 Transit Gateway VPC attachments

Does not support accepting / rejecting attachments at this time.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

ec2_transit_gateway_vpc_attachment
ec2_transit_gateway_vpc_attachment_info

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
@gravesm - I can't reproduce the failure in my local account, is there any chance you could take a look and see if something's blocked in the logs?

**Comment by gravesm** [comment]
Sure, I'll see if I can figure out what's going on.

**Comment by neilkatin** [comment]
For what it's worth: I have tried the branched code and it works for me.

Being able to actually attach a transit gateway to a VPC is an essential task to make use of Transit Gateways.

**Comment by tremble** [comment]
> For what it's worth: I have tried the branched code and it works for me.

Thanks for trying that out, I suspect Amazon's doing something 'clever' behind the scenes.  The CI account is relatively restricted so there's probably a missing permission that's not being exposed, possibly even one that's only needed the very first time you attach a VPC (Amazon does some interesting things behind the scenes in a few places)

**Comment by gravesm** [comment]
I can see the attachment gets created, but it just sits in the pending state for a while and then eventually moves to failed. There's nowhere I can find that provides any information on why it failed. I'll keep poking around at it, but if you have any suggestions as to where to look for more info on why it failed, I'd be interested in hearing them.

**Comment by tremble** [comment]
@gravesm Looks like @jillr found the kind of thing I was referring to, sorry for not responding.

**Review by alinabuzachis — APPROVED** [review]

**Pull request merged**
