### PR TITLE
Add check_mode support to ec2_asg

### PR DESCRIPTION
**Pull request by mandar242**
##### SUMMARY

Added check_mode support to `ec2_asg`.

- [x] CI failure could be resolved by #1036 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_asg

### CODE REVIEW

**Comment by mandar242** [comment]
recheck

**Comment by markuman** [comment]
LGTM, can you also add a changelog fragment please?

**Review by markuman — APPROVED** [review]

**Comment by jatorcasso** [comment]
could you add more check_mode tests? for general operations like enabling/disabling metrics collection, but also idempotence check_mode tests as well. afaik each test case should cover check_mode, action, check_mode idempotence, idempotence

**Comment by mandar242** [comment]
> could you add more check_mode tests? for general operations like enabling/disabling metrics collection, but also idempotence check_mode tests as well. afaik each test case should cover check_mode, action, check_mode idempotence, idempotence

With the general behavior of the API, and the amount of time it takes to adjust the ASG configuration, it would need to add more `pause` operations, likely resulting in longer running tests, in my opinion the current tests might be good enough to test the module behavior.

Unless others have different opinion, then we can try adding more tests where appropriate.

**Comment by jatorcasso** [comment]
> > could you add more check_mode tests? for general operations like enabling/disabling metrics collection, but also idempotence check_mode tests as well. afaik each test case should cover check_mode, action, check_mode idempotence, idempotence
> 
> 
> 
> With the general behavior of the API, and the amount of time it takes to adjust the ASG configuration, it would need to add more `pause` operations, likely resulting in longer running tests, in my opinion the current tests might be good enough to test the module behavior.
> 
> 
> 
> Unless others have different opinion, then we can try adding more tests where appropriate.
> 
> 

Can you add waiters?

**Review by jillr — APPROVED** [review]

**Pull request merged**
