### PR TITLE
Big Black PR

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

In preparation for 6.0.0 we agreed to mass apply the black formatter to our code base.

Hopefully we're only a couple of weeks out now, and we're much more on top of our PRs than we used to be. This is the big PR...

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/
tests/

##### ADDITIONAL INFORMATION

There are two commits, the first "pre-tunes" a few things so that they're not exploded into lots of extra lines, or squashed into one line. The second is just the result of `black plugins/ tests/`

### CODE REVIEW

**Review by alinabuzachis — COMMENTED** [review]
@tremble Please add a changelog fragment.

**Comment by tremble** [comment]
> @tremble Please add a changelog fragment.

Done

**Review by markuman — APPROVED** [review]

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
regate

**Review by jillr — APPROVED** [review]
Manually merging

**Pull request merged**
