### PR TITLE
aws modules: fix examples to use FQCN for builtin modules/plugins

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
aws modules: fix examples to use FQCN for builtin modules/plugins

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
CC @felixfontein

**Comment by tremble** [comment]
@Andersson007 Unfortunately we don't have the bot available to us yet hopefully @jillr or @s-hertel would be able to retrigger the tests once they're online.

**Comment by Andersson007** [comment]
@tremble thanks

**Comment by Andersson007** [comment]
thanks everyone for reviewing and merging!

**Pull request merged**
