### PR TITLE
Added functionality to Lambda module for Container based Lambdas

### PR DESCRIPTION
**Pull request by gen2fish**
##### SUMMARY
This PR adds functionality to the existing lambda module to create and manage container based lambdas

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lambda

### CODE REVIEW

**Comment by markuman** [comment]
@gen2fish 
Thank you for the PR.

The sanity checks are failing

```
ERROR: Found 2 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/lambda.py:0:0: doc-missing-type: Argument 'image_uri' in argument_spec uses default type ('str') but documentation doesn't define type
ERROR: plugins/modules/lambda.py:0:0: undocumented-parameter: Argument 'image_uri' is listed in the argument_spec, but not documented in the module documentation
```

Therefore the integrationtests are not running.  
You need to expand the documentation section. It would be also helpful if you complete the example section with the usage of the nre parameters. And the same for the integrationtest.
And at least you'll need a changelog fragment :)

**Comment by gen2fish** [comment]
blocked waiting on https://github.com/mattclay/aws-terminator/pull/178

**Comment by jillr** [comment]
recheck

**Comment by gen2fish** [comment]
recheck

**Comment by alinabuzachis** [comment]
@gen2fish It seems sanity of falling because of:

`
ERROR: Found 1 pep8 issue(s) which need to be resolved:
2275 | 2021-11-22 16:05:06.273885 \| fedora-34 \| ERROR: plugins/modules/lambda.py:438:5: E303: too many blank lines (3)
`

Could you please address it? Thank you.

**Comment by alinabuzachis** [comment]
@gen2fish Since the lambda* modules has been migrated to https://github.com/ansible-collections/amazon.aws, could you please re-open this PR against  https://github.com/ansible-collections/amazon.aws? Thank you.

**Pull request closed without merging**
