### PR TITLE
SSM connection plugin - Add encryption tests

### PR DESCRIPTION
**Pull request by tremble**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1746

##### SUMMARY

Expand on the aws_ssm connection integration tests 

- Follow up on suggestion to use ssm_parameter to locate AMIs
- Add tests for connection using encrypted buckets

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

aws_ssm

### CODE REVIEW

**Comment by tremble** [comment]
@markuman added your ssm_parameter suggestion

**Comment by markuman** [comment]
hmm

>     "msg": "Failed to access SSM parameter /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2 (AccessDenied)"

The parameter itself is correct

```
ok: [localhost] => {
    "lookup('aws_ssm', '/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2')": "ami-01ef0a53b405a1b2b"
}
```

**Comment by tremble** [comment]
@markuman Yeah, I've tested it locally.  https://github.com/mattclay/aws-terminator/pull/255 is the missing permission.

**Comment by tremble** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Pull request merged**
