### PR TITLE
Update the name attribute value in the examples

### PR DESCRIPTION
**Pull request by priyadarshu**
## Problem-

- All the examples had same **name** key value irrespective of different purposes of the tasks

## Action taken -

- Made changes in the name of the tasks under examples
- Corrected it with relevant  **name** key value to the comments of the task

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

-
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@jatorcasso Could you please review this? Thanks in advance.

**Review by jatorcasso — APPROVED** [review]
LGTM

**Review by markuman — APPROVED** [review]

**Comment by markuman** [comment]
@priyadarshu thank for your first controbution!

**Comment by Akasurde** [comment]
@priyadarshu Thanks for working on this.

**Pull request merged**
