### PR TITLE
Fix aws_ssm fails when gathering facts

### LINKED ISSUE #113: ssm connection plugin fails at gathering facts
##### SUMMARY

Using the ssm plugin, playbooks fail at the gathering facts stage, with:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: invalid literal for int() with base 10: "echo $'\\n'$?"
fatal: [i-xxxxx]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

If using `gather_facts: false`, the same error occurs at the first task

As far as I can tell, SSM is configured correctly: I can run `aws ssm start-session --target i-xxxxx` from my ansible host and successfully get a shell on the target host.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ssm connection plugin

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.8/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['aws_ec2']
```

##### OS / ENVIRONMENT

Both the instance running Ansible and the target (SSM-managed) instance are regular ubuntu 20.04 AMIs

##### STEPS TO REPRODUCE

* Launch 2 EC2 instances running Ubuntu 20.04 (in same AWS region)
* Install ansible, boto3, aws cli & sms plugin on first instance
* Run AWS Systems Manager quick start (using default roles & choosing all instances as targets)
* confirm that SSM can start a shell from Ansible to second instance: `aws ssm start-session --target i-xxxxx` 
* Enable ansible aws_ec2 inventory plugin
* Run the following playbook with the attached inventory config:

```yaml
# Playbook

- hosts: all
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_region: eu-west-2 # substitute for your region
  tasks:
    - name: test
      command:
        cmd: ls -l
```

```yaml
# aws_ec2.yaml inventory

plugin: aws_ec2
regions:
  - eu-west-2
keyed_groups:
  - prefix: tag
    key: tags
  - prefix: aws_region
    key: placement.region
hostnames:
  - instance-id
compose:
  ansible_host: instance-id
```

Run:
```
ansible-playbook -i aws_ec2.yaml -c community.aws.aws_ssm test-playbook.yaml
```

##### EXPECTED RESULTS

Playbook runs successfully with no errors

##### ACTUAL RESULTS

Playbook errors on gathering facts stage, with:

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: invalid literal for int() with base 10: "echo $'\\n'$?"
fatal: [i-xxxxx]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

with `-vvvv` verbosity:

```
ansible-playbook 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.8/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible-playbook
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/ubuntu/aws_ec2.yaml inventory source with aws_ec2 plugin
Loading callback plugin default of type stdout, v2.0 from /home/ubuntu/.local/lib/python3.8/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: test_ssm.yaml ****************************************************************************************************************************************************************************************
Positional arguments: test_ssm.yaml
verbosity: 4
connection: community.aws.aws_ssm
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/ubuntu/aws_ec2.yaml',)
forks: 5
1 plays in test_ssm.yaml

PLAY [all] *****************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
task path: /home/ubuntu/test_ssm.yaml:1
<i-xxxxx> ESTABLISH SSM CONNECTION TO: i-xxxxx
<i-xxxxx> SSM COMMAND: ['/usr/local/bin/session-manager-plugin', '{"SessionId": "i-xxxxx-yyyyy", "TokenValue": "XXXXX", "StreamUrl": "wss://ssmmessages.eu-west-2.amazonaws.com/v1/data-channel/i-yyyyy-zzzzz?role=publish_subscribe", "ResponseMetadata": {"RequestId": "xxxx-xxxx-xxxx-xxxx", "HTTPStatusCode": 200, "HTTPHeaders": {"x-amzn-requestid": "xxxx-xxxx-xxxx-xxxx-xxxx", "content-type": "application/x-amz-json-1.1", "content-length": "626", "date": "Fri, 19 Jun 2020 14:41:52 GMT"}, "RetryAttempts": 0}}', 'eu-west-2', 'StartSession', '', '{"Target": "i-xxxxx"}', 'https://ssm.eu-west-2.amazonaws.com']
<i-xxxxx> SSM CONNECTION ID: i-xxxx-xxxxx
<i-xxxxx> EXEC echo ~
<i-xxxxx> _wrap_command: 'echo XXXXX
echo ~
echo $'\n'$?
echo YYYYY
'
<i-xxxxx> EXEC stdout line: 
<i-xxxxx> EXEC stdout line: Starting session with SessionId: i-xxxxx-yyyyy
<i-xxxxx> EXEC remaining: 60
<i-xxxxx> EXEC stdout line: $ stty -echo
<i-xxxxx> EXEC stdout line: PS1=''
<i-xxxxx> EXEC stdout line: echo XXXXX
<i-xxxxx> EXEC stdout line: echo ~
<i-xxxxx> EXEC stdout line: echo $'\n'$?
<i-xxxxx> EXEC stdout line: echo YYYYY
<i-xxxxx> POST_PROCESS: echo ~
echo $'\n'$?
<i-xxxxx> ssm_retry: attempt: 0, caught exception(invalid literal for int() with base 10: "echo $'\\n'$?") from cmd (echo ~...), pausing for 0 seconds
<i-xxxxx> CLOSING SSM CONNECTION TO: i-xxxxx
<i-xxxxx> TERMINATE SSM SESSION: i-xxxxx-yyyyy
<i-xxxxx> ESTABLISH SSM CONNECTION TO: i-xxxxx
<i-xxxxx> SSM COMMAND: ['/usr/local/bin/session-manager-plugin', '{"SessionId": "i-xxxxx-yyyyy", "TokenValue": "XXXXX", "StreamUrl": "wss://ssmmessages.eu-west-2.amazonaws.com/v1/data-channel/i-yyyyy-zzzzz?role=publish_subscribe", "ResponseMetadata": {"RequestId": "xxxx-xxxx-xxxx-xxxx-xxxx", "HTTPStatusCode": 200, "HTTPHeaders": {"x-amzn-requestid": "xxxx-xxxx-xxxx-xxxx-xxxx", "content-type": "application/x-amz-json-1.1", "content-length": "626", "date": "Fri, 19 Jun 2020 14:41:53 GMT"}, "RetryAttempts": 0}}', 'eu-west-2', 'StartSession', '', '{"Target": "i-xxxxx"}', 'https://ssm.eu-west-2.amazonaws.com']
<i-xxxxx> SSM CONNECTION ID: i-xxxx-xxxx
<i-xxxxx> EXEC echo ~
<i-xxxxx> _wrap_command: 'echo YYYYY
echo ~
echo $'\n'$?
echo ZZZZZ
'
<i-xxxxx> EXEC stdout line: 
<i-xxxxx> EXEC stdout line: Starting session with SessionId: i-xxxx-yyyy
<i-xxxxx> EXEC remaining: 60
<i-xxxxx> EXEC stdout line: $ stty -echo
<i-xxxxx> EXEC stdout line: PS1=''
<i-xxxxx> EXEC stdout line: echo YYYYY
<i-xxxxx> EXEC stdout line: echo ~
<i-xxxxx> EXEC stdout line: echo $'\n'$?
<i-xxxxx> EXEC stdout line: echo ZZZZZ
<i-xxxxx> POST_PROCESS: echo ~
echo $'\n'$?
<i-xxxxx> CLOSING SSM CONNECTION TO: i-xxxxx
<i-xxxxx> TERMINATE SSM SESSION: i-xxxxx-yyyyy
The full traceback is:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ansible/plugins/action/gather_facts.py", line 79, in run
    res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 780, in _execute_module
    self._make_tmp_path()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 343, in _make_tmp_path
    tmpdir = self._remote_expand_user(self.get_shell_option('remote_tmp', default='~/.ansible/tmp'), sudoable=False)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 664, in _remote_expand_user
    data = self._low_level_execute_command(cmd, sudoable=False)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 1075, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/home/ubuntu/.ansible/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 197, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/home/ubuntu/.ansible/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 389, in exec_command
    returncode, stdout = self._post_process(stdout, mark_begin)
  File "/home/ubuntu/.ansible/collections/ansible_collections/community/aws/plugins/connection/aws_ssm.py", line 442, in _post_process
    returncode = int(stdout.splitlines()[-2])
ValueError: invalid literal for int() with base 10: "echo $'\\n'$?"
fatal: [i-xxxxx]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

### PR DESCRIPTION
**Pull request by richardsonky**
Depends-On: https://github.com/ansible-collections/community.aws/pull/621

##### SUMMARY
Fixes #113 

aws_ssm fails when gathering facts.  This fix incorporates some code submitted by others, but also works on windows which others haven't done yet.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
aws_ssm

##### ADDITIONAL INFORMATION

Fixes aws_ssm connection plugin when gathering facts.  Uses code a few others submitted but also fixes windows.  
Changed logic in the exec_command, wrap_command, and post_process functions that help to unify the output from windows and linux to make it easier to locate return values of the commands.

We have been running this in our environment for over a month and it is working without issue against win2016, win2019, centos7, suse15, and rhel7 ec2 instances.

### CODE REVIEW

**Comment by tremble** [comment]
Thanks for taking the time to submit this PR.

I've not got the time to review it right now, however the sanity tests are throwing some errors that should be fixed:

```
ERROR: Found 2 pep8 issue(s) which need to be resolved:
ERROR: plugins/connection/aws_ssm.py:447:14: E121: continuation line under-indented for hanging indent
ERROR: plugins/connection/aws_ssm.py:457:70: E261: at least two spaces before inline comment
```

**Comment by richardsonky** [comment]
I had to revert the linux cmd f(printf ...) statements that were suggested by others, it wasn't going to pass the python2.6 checks.  I went back to the old cmd method and modified it with ';'s so it works as expected and passes the python2.6 tests.  

I also modified a few of the logging lines while i was in here to have it log in vvvv so that it doesn't show up in debug logs, only in connection.  I've tested in each OS we support and it is working as expected.

**Comment by goneri** [comment]
> I had to revert the linux cmd f(printf ...) statements that were suggested by others, it wasn't going to pass the python2.6 checks. I went back to the old cmd method and modified it with ';'s so it works as expected and passes the python2.6 tests.
> 
> I also modified a few of the logging lines while i was in here to have it log in vvvv so that it doesn't show up in debug logs, only in connection. I've tested in each OS we support and it is working as expected.

For the record, we now only support Py38+. It's a pretty recent change thus.

**Comment by goneri** [comment]
Can you quickly explain how you do you tests? Maybe you've got a test playbook?

**Comment by richardsonky** [comment]
Our tests are not really official but seem to work ok.  I have a CF template to build an ec2 instance for each OS we support at our company.  We have a system in place to kick off our playbooks using cloudwatch events, step functions, and fargate.  It will run through our standard playbook to configure the ec2.  We visually look to see if the playbooks ran correctly.   I've found a few bugs using this test so it seems work, though not very automated and probably doesn't test every possibility.

**Comment by wilinger** [comment]
Did you also test on Ubuntu 20.04? Works on Amazon Linux but not Ubuntu for me

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: invalid literal for int() with base 10: "echo $'\\n'$?"
fatal: [test_ubuntu1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}`

**Comment by richardsonky** [comment]
I did not test ubuntu, it's not one of the OSs we support, however i think i found the problem.  There were two issues.  The first is it did not detect the proper command output for ubuntu, so i modified the check to ensure that it finds the right output.  Once that worked it then did not like the old method of wrapping the command, but it does work with the new printf statements.  I put the printf statements back and ubuntu is working.  I don't have an extended playbook for ubuntu, i pretty much just did a quick gather facts and it works.  I also tested ubuntu 18.04 and it works now as well.  

I redid my tests for each OS we support and they work still.  So if the automated testing doesn't check old python versions anymore then it should pass those checks.

Let me know if that works ok for you now.

**Comment by richardsonky** [comment]
Looks like it's still failing on those older versions of python that do not support f strings.  Do we need to find a solution that works with all those older versions still?

**Comment by wilinger** [comment]
> I did not test ubuntu, it's not one of the OSs we support, however i think i found the problem. There were two issues. The first is it did not detect the proper command output for ubuntu, so i modified the check to ensure that it finds the right output. Once that worked it then did not like the old method of wrapping the command, but it does work with the new printf statements. I put the printf statements back and ubuntu is working. I don't have an extended playbook for ubuntu, i pretty much just did a quick gather facts and it works. I also tested ubuntu 18.04 and it works now as well.
> 
> I redid my tests for each OS we support and they work still. So if the automated testing doesn't check old python versions anymore then it should pass those checks.
> 
> Let me know if that works ok for you now.

The change seemed to have broke something because it's not working for both Ubuntu and Amazon Linux now. Counts down 'EXEC remaining' and loops.  What seemed to work for me for both Amazon Linux and Ubuntu was the patched code posted on #113 

`
<i-01a11b1adbdd11111> EXEC stdout line: 
<i-01a11b1adbdd11111> EXEC stdout line: Starting session with SessionId: botocore-session-11111111111-0f1db111f64ee111c
<i-01a11b1adbdd11111> EXEC remaining: 60
<i-01a11b1adbdd11111> EXEC remaining: 59
<i-01a11b1adbdd11111> EXEC stdout line: $ stty -echo
<i-01a11b1adbdd11111> EXEC stdout line: PS1=''
<i-01a11b1adbdd11111> EXEC stdout line: printf '%s\n' 'VKbBEZmnukenWpSHnhjpeLsytB';
<i-01a11b1adbdd11111> EXEC stdout line: echo | ( umask 77 && mkdir -p "` echo /tmp `"&& mkdir "` echo /tmp/ansible-tmp-1625158982.2448153-792605-17192929165503 `" && echo ansible-tmp-1625158982.2448153-792605-17192929165111="` echo /tmp/ansible-tmp-1625158982.2448153-792605-17192929165503 `" );
<i-01a11b1adbdd11111> EXEC stdout line: printf '\n%s\n%s\n' "$?" 'iWzKicCLGXsTVUgEgQFTjzkFtq';
<i-01a11b1adbdd11111> EXEC stdout line: $ VKbBEZmnukenWpSHnhjpeLsysa
<i-01a11b1adbdd11111> EXEC stdout line: ansible-tmp-1625158982.2448153-792605-17192929165111=/tmp/ansible-tmp-1625158982.2448153-792605-17192929165111
<i-01a11b1adbdd11111> EXEC stdout line: 
<i-01a11b1adbdd11111> EXEC stdout line: 0
<i-01a11b1adbdd11111> EXEC stdout line: iWzKicCLGXsTVUgEgQFTjzkFtq
<i-01a11b1adbdd11111> EXEC remaining: 58
<i-01a11b1adbdd11111> EXEC remaining: 57
<i-01a11b1adbdd11111> EXEC remaining: 56
<i-01a11b1adbdd11111> EXEC remaining: 55
<i-01a11b1adbdd11111> EXEC remaining: 54`

**Comment by richardsonky** [comment]
Sorry about that, i had a typo when i transferred the edits to this repo.  Please test again and let me know if that worked.  I've tested on ansible linux and ubuntu and it appears to work ok for me.

**Comment by wilinger** [comment]
@richardsonky It's working now on both Ubuntu and Amazon Linux now. Thanks for the fix!

**Comment by richardsonky** [comment]
> > I had to revert the linux cmd f(printf ...) statements that were suggested by others, it wasn't going to pass the python2.6 checks. I went back to the old cmd method and modified it with ';'s so it works as expected and passes the python2.6 tests.
> > I also modified a few of the logging lines while i was in here to have it log in vvvv so that it doesn't show up in debug logs, only in connection. I've tested in each OS we support and it is working as expected.
> 
> For the record, we now only support Py38+. It's a pretty recent change thus.

@goneri 
Looks like the checks for older python version is still a problem since they don't support f strings.   Do we need to fix the code to work with those older versions?

**Comment by goneri** [comment]
> > > I had to revert the linux cmd f(printf ...) statements that were suggested by others, it wasn't going to pass the python2.6 checks. I went back to the old cmd method and modified it with ';'s so it works as expected and passes the python2.6 tests.
> > > I also modified a few of the logging lines while i was in here to have it log in vvvv so that it doesn't show up in debug logs, only in connection. I've tested in each OS we support and it is working as expected.
> > 
> > 
> > For the record, we now only support Py38+. It's a pretty recent change thus.
> 
> @goneri
> Looks like the checks for older python version is still a problem since they don't support f strings. Do we need to fix the code to work with those older versions?

I mean, we support py38+ on the controller side. We continue to support py2 on the remote nodes.

**Comment by goneri** [comment]
Ansible-test still checks with Python 2.6 to 3.7. To keep it quiet, we use ignore files to disable some checks: https://github.com/ansible-collections/community.aws/tree/main/tests/sanity

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
I've just pushed https://github.com/ansible-collections/community.aws/pull/621 to extend these filters.

**Comment by jillr** [comment]
> For the record, we now only support Py38+. It's a pretty recent change thus.

We support 3.6+ for the AWS collections, but we definitely don't need to be testing on 2.x any longer.

**Comment by damoun** [comment]
Is there any news about this PR ? Looks like #621 is not needed anymore.

**Comment by vranyes** [comment]
This PR fixes this issue for me as well - any chance this can be merged?

**Comment by kloveday2** [comment]
This PR also fixes the issue for me. What left to be done to get it merged?

**Comment by richardsonky** [comment]
not sure what i'm doing, so closing and will reopen a new one

**Comment by Leon-Africa** [comment]
Reference: https://github.com/ansible-collections/community.aws/pull/948#issuecomment-1230223415

**Pull request closed without merging**
