### PR TITLE
efs : add elastic throughput_mode

### PR DESCRIPTION
**Pull request by KamilBlaz**
##### SUMMARY

Fixes: #1884 
Add `elastic` throughput mode  in efs module

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

efs
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by markuman** [comment]
@KamilBlaz thanks again. Same as in your other PR. Can you please add changelog fragment and append the integration test?

**Comment by lotyp** [comment]
This would be great feature to have, was searching for solution, and I see that it is already done. What is needed to get it merged?

**Comment by lotyp** [comment]
@markuman I have created updated pull request with changes, that you have requested - https://github.com/ansible-collections/community.aws/pull/2026

**Comment by tremble** [comment]
closing as "duplicate" of #2026

**Pull request closed without merging**
