### PR TITLE
Fix non-matching defaults in docs

### PR DESCRIPTION
**Pull request by felixfontein**
Depends-On: https://github.com/ansible-collections/community.aws/pull/1579

##### SUMMARY
Fix various non-matching `default` values exposed by https://github.com/ansible/ansible/pull/79267.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Comment by felixfontein** [comment]
recheck

**Review by markuman — APPROVED** [review]

**Comment by felixfontein** [comment]
recheck

**Comment by felixfontein** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by felixfontein** [comment]
@markuman @tremble thanks for reviewing this and getting it merged!

**Pull request merged**
