### PR TITLE
Prep 3.2.0 Release

### PR DESCRIPTION
**Pull request by markuman**
##### SUMMARY
Release community.aws 3.2.0

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME
entire collection

### CODE REVIEW

**Comment by markuman** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Review by marknet15 — APPROVED** [review]

**Comment by marknet15** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
Oh boy .... those who can read have a clear advantage!

> ERROR! Failed to resolve the requested dependencies map. Got the candidate amazon.aws:3.1.2-dev21 (dependency of community.aws:3.1.1-dev29) which didn't satisfy all of the following requirements:

The CI check will fail as long as amazon.aws 3.2.0 is not released, because of the requirements in the galaxy file

`  amazon.aws: '>=3.2.0'`

So this PR is blocked by https://github.com/ansible-collections/amazon.aws/pull/759

**Pull request closed without merging**
