### PR TITLE
Add ResourceType on ec2 snapshot copy

### PR DESCRIPTION
**Pull request by bplaxco**
##### SUMMARY
Fixes this issue that shows up when tags are specified:

```
An error occurred waiting for the snapshot to become available.: An
error occurred (InvalidParameterValue) when calling the CopySnapshot
operation: Tag specification resource type must have a value
```

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
ec2_snapshot_copy

##### ADDITIONAL INFORMATION

```paste below
# before

botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CopySnapshot operation: Tag specification resource type must have a value                              
fatal: [localhost]: FAILED! => {                                                                                                                                                                   
    "boto3_version": "1.24.57",                                                                                                                                                                    
    "botocore_version": "1.27.58",                                                                                                                                                                 
    "changed": false,                                                                                                                                                                              
    "error": {                                                                                                                                                                                     
        "code": "InvalidParameterValue",                                                                                                                                                           
        "message": "Tag specification resource type must have a value"                                                                                                                             
    },  
....


# after  (no error message)

changed: [localhost] => {                                                                                                                                                                          
    "changed": true,                                                                                                                                                                               
    "invocation": {                                                                                                                                                                                
        "module_args": {       
.....
```

### CODE REVIEW

**Review by tremble — CHANGES_REQUESTED** [review]
Hi @bplaxco,

Thanks for taking the time to submit this PR.  The change itself looks correct, however I'd ask for two minor additions:

1) Please add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to
2) (optional) It would be really good if you could add an integration test.  These are (in essence) just an an Ansible role which try to systematically exercise the module to test it behaves as expected, and live in `tests/integration/targets/`.  A good starting point might be https://github.com/ansible-collections/amazon.aws/tree/main/tests/integration/targets/ec2_snapshot from the amazon.aws collection

**Comment by bplaxco** [comment]
Changelog fragment added.

Looking into the tests.

**Comment by bplaxco** [comment]
@tremble in the [zuul ouput](https://ansible.softwarefactory-project.io/zuul/build/e01e56bff92b48e4a1d154e7e02734c4/console) I get:

```json
    "error": {
        "code": "UnauthorizedOperation",
        "message": "You are not authorized to perform this operation. Encoded authorization failure message: SZOho26QkeN31KcOxBTUnC_sBSeRa3G9qqAmqJOLtkkAiUvLcOIlJVojSNLkyZa7MXEHWbTOAtc5aemsWR_tKiqEZtwr5OlwXk4PbtKTtj0NdpDaBeDs1q-Mpt7zDktDjJmk41tSPe-Rjjqe1ftFJhuZ76rQKHOXEeLol1QsaW2kA9x74EEf6gbr13kMUi2CyF3D-XTFMLkpZj-XShxzE9QbF1xvmnvwxIbmwuVk0PWFUX8dKbQbeB4K_jSCBLIV5Ag3Rio0Foc4h6uYfBmTz_vOR7J2ukyrRdgn5dwIc_78jFpa2DSqPa93EbGXeXjW6fTtzFvsExeRynD7-QBDY4iZEYGE2inBGZHZO7elmhh4Ie9G-xV6g2hBZVlWShrDzxGoJjanOiqTxl3530TxVRO-YO3kIzDbG55DouvtyOGdJyQntxyeIB2eR0gZhI5maCAcsD2YODtRyhwIDIXhGiBKmB4GmZ90ZgfQ0zHkLf4aLr5xxZcpeqf3juVUpMUMdOIWQ_VIdldVmPvx13e4FrsVACt4509Uh1vt5R7N-vX6YSh5g9CDrJ8"
    }
```

The module args passed in to ec2_snapshot_copy seem legit from what I know about the module, would someone be able to take a look and confirm the service account used has the right permissions? Or would you rather me mark the tests as disabled or something like that?

**Review by colbyshores — APPROVED** [review]
The change on line 141 to declare type ['snapshot'] in ec2_snapshot_copy.py looks good to me

**Comment by bplaxco** [comment]
@tremble 

I went ahead and removed the tests to get the MR through since they were marked as optional, but since they seemed to be failing because of a permission issue with the service account running them, I kept them in the history[1] in case we want to pull them back in.

Feel free to ping me on gchat at work if you'd like to sync up on getting the test running ^\_^
    
[1] The tests are still on aec7b2fd397337fced67d9b4846fbeed74db61cc

**Comment by bplaxco** [comment]
Hey @tremble just wanted to see if you need anything else from me on this ^_^

**Review by ringmany — APPROVED** [review]

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
@bplaxco sorry about the delay here.  LGTM

**Pull request merged**
