### PR TITLE
[WIP] add algorithm_type option for elb_target_group

### PR DESCRIPTION
**Pull request by markuman**
##### SUMMARY
Add option `algorithm_type` for `elb_target_group`

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
elb_target_group

### CODE REVIEW

**Comment by markuman** [comment]
d'oh

> The following attributes are supported only if the load balancer is an Application Load Balancer and the target is an instance or an IP address

**Comment by sakar97** [comment]
> d'oh
> 
> > The following attributes are supported only if the load balancer is an Application Load Balancer and the target is an instance or an IP address

Hi @markuman , did you find any workarounds?

**Comment by tremble** [comment]
@sakar97 the access_key is approximately a username, Amazon don't treat it as a secret so we don't.

**Comment by markuman** [comment]
> > d'oh
> > > The following attributes are supported only if the load balancer is an Application Load Balancer and the target is an instance or an IP address
> 
> Hi @markuman, did you find any workarounds? 

The target group itself does not know if it is attached to an ALB, ELB  Classic or NLB imho.  
We can exclude NLB to match the attribute thing if target type is instance or ip and the protocol is http or https.  
But thant the elb_target_group can still fail if it is attached to a classic ELB.

**Comment by markuman** [comment]
closing for the benefit of https://github.com/ansible-collections/community.aws/pull/1016

**Pull request closed without merging**
