### PR TITLE
Improve doc of ec2_launch_template module

### PR DESCRIPTION
**Pull request by sebastien-rosset**
##### SUMMARY

Add information about how the ec2_launch_template handles initial creation of the launch template, or creation of a new version of the launch template.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ec2_launch_template

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sebastien-rosset** [comment]
The CI build fails because of #902

**Review by markuman — APPROVED** [review]

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Review by marknet15 — APPROVED** [review]

**Review by tremble — APPROVED** [review]

**Pull request merged**
