### PR TITLE
Fix idempotency and logic to update existing aggregator

### PR DESCRIPTION
**Pull request by ichekaldin**
##### SUMMARY

`describe_configuration_aggregators` method returns output similar
to the following:

```
{
    "ConfigurationAggregators": [
        {
            "ConfigurationAggregatorName": "test-name",
            "ConfigurationAggregatorArn": "arn:aws:config:us-east-1:123412341234:config-aggregator/config-aggregator-xbxbvyq5",
            "OrganizationAggregationSource": {
                "RoleArn": "arn:aws:iam::123412341234:role/my-role",
                "AllAwsRegions": true
            },
            "CreationTime": 1619030767.047,
            "LastUpdatedTime": 1626463216.998
        }
    ]
}
```

As a result, lines 134-136 fail:

```
    del current_params['ConfigurationAggregatorArn']
    del current_params['CreationTime']
    del current_params['LastUpdatedTime']
```
as they try to delete attributes from the `current_params` as opposed
to `current_params['ConfigurationAggregators'][0]`.

The error message is:
```
KeyError: 'ConfigurationAggregators'
```

Additionally, if no `account_sources` attribute is specified, the module
fails idempotency check, because in that case `AccountAggregationSources`
attribute is present in `params`, but not in `current_params`.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

aws_config_aggregator

### CODE REVIEW

**Comment by ichekaldin** [comment]
I see that **ansible/check** failed two tests:

- ansible-galaxy-importer - I can't clearly see what the error is.

- ansible-test-cloud-integration-aws-py36_2 - the error is:
```
ERROR: The 1 integration test(s) listed below (out of 20) failed. See error output above for details:
ec2_vpc_endpoint_service_info
```

I haven't modified any files related to `ec2_vpc_endpoint_service_info` as part of this PR.

Am I missing anything obvious?

**Comment by alinabuzachis** [comment]
recheck

**Comment by ichekaldin** [comment]
@alinabuzachis It looks like the tests fail with the same errors.

**Comment by tremble** [comment]
@ichekaldin Sorry about that, the move to Zuul caused all sorts of fun.

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
@ichekaldin While they're not run in CI due to constraints with AWS Config (eg. you can't have multiple aggregators) There are some basic integration tests for aws_config (including the aggregator)

https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/aws_config/tasks/main.yaml

Please could you update the tests to include idempotency tests and some regression tests for the issues you hit.

**Comment by ichekaldin** [comment]
@tremble I added a test to validate that specifying empty list of accounts and the organization source works:

```
    - name: test resource_type configuration_aggregator with organization_source parameter
      aws_config_aggregator:
        name: random_name
        state: present
        account_sources: []
        organization_source:
          all_aws_regions: true
          role_arn: "{{ config_iam_role.arn }}"
      register: output
      ignore_errors: true
```

Would that be sufficient?

**Comment by ichekaldin** [comment]
@tremble Sorry to keep bumping this - I'd love for this fix to get merged before the next release. What do you think about the test I added?

**Review by tremble — APPROVED** [review]
Basic tests seem to show it's working

**Comment by tremble** [comment]
@ichekaldin Sorry it took so long to get back to this review.

**Pull request merged**
