### PR TITLE
Minor documentation fix [aws_api_gateway]

### PR DESCRIPTION
**Pull request by sakar97**
##### SUMMARY

Fix doc.

##### ISSUE TYPE

- Docs Pull Request
##### COMPONENT NAME

aws_api_gateway
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by markuman — APPROVED** [review]

**Comment by markuman** [comment]
shipit

**Comment by sakar97** [comment]
Hi @markuman  what does shipit means?

**Comment by Akasurde** [comment]
@sakar97 'shipit' is an agreement that code looks good and can be merged. Maintainers of the module has special rights with 'shipit'. If two maintainers 'shipit', bot will merge the PR once the CI is green.

**Comment by Akasurde** [comment]
@sakar97 Thanks for the contribution, look forward for more contribution from your side.

**Comment by sakar97** [comment]
Thanks, @Akasurde for explaining it so well.

**Pull request merged**
