### PR TITLE
Fix target group remove / add logic

### LINKED ISSUE #492: ec2_asg not updating target group
##### SUMMARY
Previously reported at https://github.com/ansible/ansible/issues/65008.  But in the repo migrations it looks like it got closed without ever getting fixed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_asg

##### ANSIBLE VERSION

```
ansible 2.10.6
  config file = None
  configured module search path = ['/home/msven/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/msven/python3/venv/lib/python3.6/site-packages/ansible
  executable location = /home/msven/python3/venv/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

##### CONFIGURATION

```
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATH) = ['/home/msven/git/ansible_collections', '/home/msven']
```

##### STEPS TO REPRODUCE

1. Create new ec2 auto scaling group
2. Create new target group or attach existing target group via target_group_arns property under ec2_asg module.
3. Now create new target group and update target_group_arns with new arn.

##### EXPECTED RESULTS

* New target group should get attached to asg and old should be removed.

##### ACTUAL RESULTS

* Target group doesn't get updated with new arn.

### PR DESCRIPTION
**Pull request by msven**
##### SUMMARY

Fixes target group update logic to support updating target groups when the final number
of target groups attached to the asg remains the same.

Fixes #492 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_asg

##### ADDITIONAL INFORMATION

Integration tests were added to validate the change.  The following test would've previously failed the final assertion.

    - name: update autoscaling group tg2
      ec2_asg:
        name: "{{ resource_prefix }}-asg"
        launch_template: 
          launch_template_name: "{{ resource_prefix }}-lt"
        target_group_arns:
          - "{{ out_tg2.target_group_arn }}"
        desired_capacity: 1
        min_size: 1
        max_size: 1
        state: present
        wait_for_instances: yes
      register: output

    - assert:
        that:
          - "output.target_group_arns | length == 1"
          - "output.target_group_arns[0] == out_tg2.target_group_arn"

    - name: update autoscaling group remove tg2 and add tg1
      ec2_asg:
        name: "{{ resource_prefix }}-asg"
        launch_template: 
          launch_template_name: "{{ resource_prefix }}-lt"
        target_group_arns:
          - "{{ out_tg1.target_group_arn }}"
        desired_capacity: 1
        min_size: 1
        max_size: 1
        state: present
        wait_for_instances: yes
      register: output

    - assert:
        that:
          - "output.target_group_arns | length == 1"
          - "output.target_group_arns[0] == out_tg1.target_group_arn"

```paste below

```

### CODE REVIEW

**Comment by msven** [comment]
Not sure how to get the tests to re-run - the test failures seem to be issues pulling a docker image.

**Comment by tremble** [comment]
Test was failing with a linting issue:

```
06:05 ERROR: tests/integration/targets/ec2_asg/tasks/main.yml:822:7: key-duplicates: duplication of key "register" in mapping (100%)
```

**Comment by tremble** [comment]
@jillr any chance you could try the ASG tests locally my connection's currently too flakey for the slow ASG tests.

**Review by tremble — APPROVED** [review]
Changes generally look good, unfortunately I'm not able to run the ASG tests for the next week or two (they're disabled in CI due to their **very** long duration).

**Comment by msven** [comment]
ready_for_review

**Comment by tremble** [comment]
Successfully run the local tests

**Comment by tremble** [comment]
@msven, many thanks for your submission.

This fix should be available in the next release of this collection (1.5.0)

**Pull request merged**
