### PR TITLE
Delete ec2_vpc_route_table* since already promoted 

### PR DESCRIPTION
**Pull request by alinabuzachis**
While migrating `ec2_vpc_route_table` and `ec2_vpc_route_table_info` (https://github.com/ansible-collections/community.aws/pull/672) from `community.aws` to `amazon.aws`, we forget to delete the modules from the `community.aws` collection after the promotion. As of now, the modules within `community.aws` have not received any new updates, so we can remove them without backporting anything.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by markuman** [comment]
recheck

**Review by markuman — APPROVED** [review]

**Review by jatorcasso — APPROVED** [review]
These tests were actually failing occasionally due to a race conditions so lets get this one merged

**Review by jillr — APPROVED** [review]

**Comment by jatorcasso** [comment]
regate

**Comment by markuman** [comment]
regate

**Comment by alinabuzachis** [comment]
@markuman Since this is a breaking change is this something we want to backport to stable-3?

**Comment by markuman** [comment]
> @markuman Since this is a breaking change is this something we want to backport to stable-3?

Oh, yeah. You are right!

**Comment by markuman** [comment]
regate

**Comment by markuman** [comment]
regate

**Comment by jatorcasso** [comment]
regate

**Comment by goneri** [comment]
regate

**Pull request merged**
