### PR TITLE
Fix KeyError when Cluster Parameter Group is specified in rds_cluster.py

### PR DESCRIPTION
**Pull request by imesias**
##### SUMMARY

Fix KeyError when comparing state.
Fixes: [#1409 ](https://github.com/ansible-collections/community.aws/issues/1409)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

rds_cluster.py

### CODE REVIEW

**Comment by markuman** [comment]
@imesias thank you for your PR.  
Can you expand the integration test `tests/integration/targets/rds_cluster` with the case of your origin issue?  
Another thing what every PR needs, is a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments)

**Comment by imesias** [comment]
@markuman I've added the changelog fragment and I guess the below should be a sufficient test, problem is there is no db cluster parameter group in the collection to create a cluster parameter group. I could use the cli as a workaround. Please let me know if that will work.

```
... some task before to create the parameter group ...
  - name: Modify DB cluster parameter group
    rds_cluster:
      id: "{{ cluster_id }}"
      state: present
      db_cluster_parameter_group_name: "{{ new_db_parameter_group_name }}"
    register: _result_modify_db_parameter_group_name

  - assert:
      that:
      - _result_modify_db_parameter_group_name.changed
      - "'allocated_storage' in _result_modify_db_parameter_group_name"
      - _result_modify_db_parameter_group_name.allocated_storage == 1
      - "'cluster_create_time' in _result_modify_db_parameter_group_name"
      - _result_modify_db_parameter_group_name.copy_tags_to_snapshot == false
      - "'db_cluster_arn' in _result_modify_db_parameter_group_name"
      - "_result_modify_db_parameter_group_name.db_cluster_identifier == '{{ cluster_id }}'"
      - "'db_cluster_parameter_group' in _result_modify_db_parameter_group_name"
      - "'db_cluster_resource_id' in _result_modify_db_parameter_group_name"
      - "'endpoint' in _result_modify_db_parameter_group_name"
      - "'engine' in _result_modify_db_parameter_group_name"
      - _result_modify_db_parameter_group_name.engine == "{{ engine }}"
      - "'engine_mode' in _result_modify_db_parameter_group_name"
      - _result_modify_db_parameter_group_name.engine_mode == "provisioned"
      - "'engine_version' in _result_modify_db_parameter_group_name"
      - "'master_username' in _result_modify_db_parameter_group_name"
      - _result_modify_db_parameter_group_name.master_username == "{{ username }}"
      - "'port' in _result_modify_db_parameter_group_name"
      - "_result_modify_db_parameter_group_name.port == {{ new_port }}"
      - "'status' in _result_modify_db_parameter_group_name"
      - _result_modify_db_parameter_group_name.status == "available"
      - "'tags' in _result_modify_db_parameter_group_name"
      - "'vpc_security_groups' in _result_modify_db_parameter_group_name"
```

**Comment by markuman** [comment]
@imesias hm, thereretically yes. like https://github.com/ansible-collections/amazon.aws/blob/ad7a0eb22a3e108451959eceff4f1bd78ea8be7c/tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/termination_protection.yml#L47-L54  
But it's a changing aws call in this case, and we must take care that the ressources are also removed when the test is finished (_succeeded or failed_).  
What do you think @alinabuzachis?

**Comment by imesias** [comment]
@markuman @alinabuzachis Expanded integration tests for parameter group test case. Uses cli to create the parameter group and a cleanup task added as well.

**Comment by alinabuzachis** [comment]
> @imesias hm, thereretically yes. like https://github.com/ansible-collections/amazon.aws/blob/ad7a0eb22a3e108451959eceff4f1bd78ea8be7c/tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/termination_protection.yml#L47-L54
> But it's a changing aws call in this case, and we must take care that the ressources are also removed when the test is finished (_succeeded or failed_).
> What do you think @alinabuzachis?

Agree. If I find some time I’ll work on adding this new module.

**Review by alinabuzachis — APPROVED** [review]
@imesias thank you for working on this. LGTM!

**Comment by imesias** [comment]
@markuman @alinabuzachis hmmm, Seems there are 3 issues.

1. It looks like I'll need to add `engine` to the playbook module args for that modify task.

```
TASK [rds_cluster : Modify DB cluster parameter group] *************************
task path: /home/zuul/.ansible/collections/ansible_collections/community/aws/tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_modify.yml:179
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_rds_cluster_payload_f_en1hek/ansible_rds_cluster_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/rds.py", line 206, in call_method
    result = AWSRetry.jittered_backoff(catch_extra_error_codes=retry_codes)(method)(**parameters)
  File "/tmp/ansible_rds_cluster_payload_f_en1hek/ansible_rds_cluster_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py", line 119, in _retry_wrapper
    return _retry_func(
  File "/tmp/ansible_rds_cluster_payload_f_en1hek/ansible_rds_cluster_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py", line 69, in _retry_func
    return func()
  File "/tmp/ansible_rds_cluster_payload_f_en1hek/ansible_rds_cluster_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/modules.py", line 329, in deciding_wrapper
    return unwrapped(*args, **kwargs)
  File "/home/zuul/venv/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/zuul/venv/lib/python3.9/site-packages/botocore/client.py", line 677, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/zuul/venv/lib/python3.9/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/zuul/venv/lib/python3.9/site-packages/botocore/validate.py", line 319, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "Engine"
```
2. I will need to also look at why this conditional in the playbook is evaluating to false in the CI environment. 

```
TASK [rds_cluster : Create DB cluster parameter group if not exists] ***********
task path: /home/zuul/.ansible/collections/ansible_collections/community/aws/tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_modify.yml:168
skipping: [modify] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
```

3. It appears the attached role does not have permission to remove/cleanup a db cluster parameter group.
```
"stderr": "\nAn error occurred (AccessDenied) when calling the DeleteDBClusterParameterGroup operation: User: arn:aws:sts::XXXXXXXXXXX:assumed-role/ansible-core-ci-test-prod/prod=remote=zuul-cloud is not authorized to perform: rds:DeleteDBClusterParameterGroup on resource: arn:aws:rds:us-east-1:XXXXXXXXX:cluster-pg:test-db-parameter-group-2688144c4346-new because no identity-based policy allows the rds:DeleteDBClusterParameterGroup action"
```

I will have a look at resolving the first two, not sure who I can talk to about the number 3.

Thanks!

**Comment by imesias** [comment]
Hey @markuman @alinabuzachis, The CI AWS credentials require permission to create and remove the a `DBClusterParameterGroup` can you please add permission `rds:CreateDBClusterParameterGroup` and `rds:DeleteDBClusterParameterGroup` to allow the expanded integration test to succeed.

Kind Regards,

**Comment by markuman** [comment]
> Hey @markuman @alinabuzachis, The CI AWS credentials require permission to create and remove a `DBClusterParameterGroup` can you please add permission `rds:CreateDBClusterParameterGroup` and `rds:DeleteDBClusterParameterGroup` to the appropriate role to allow the expanded integration test to succeed.
> 
> Kind Regards,

the permissions are managed by https://github.com/mattclay/aws-terminator  
it must be expanded somewhere here: https://github.com/mattclay/aws-terminator/blob/master/aws/policy/data-services.yaml#L73-L111  
and I am not sure if the [`RdsDbCluster`] class must be also expanded https://github.com/mattclay/aws-terminator/blob/master/aws/terminator/data_services.py#L221-L244 so make sure, the cluster parameter groups are cleaned up at the end.

**Comment by imesias** [comment]
@markuman Ok, assuming then I need to open a PR with the changes to https://github.com/mattclay/aws-terminator/blob/master/aws/policy/data-services.yaml#L73-L111 as well https://github.com/mattclay/aws-terminator/blob/master/aws/policy/data-services.yaml#L73-L111  to resolve. 

Kindly confirm and I will submit shortly.

**Comment by markuman** [comment]
> @markuman Ok, assuming then I need to open a PR with the changes to https://github.com/mattclay/aws-terminator/blob/master/aws/policy/data-services.yaml#L73-L111 as well https://github.com/mattclay/aws-terminator/blob/master/aws/policy/data-services.yaml#L73-L111 to resolve.
> 
> Kindly confirm and I will submit shortly.

yes. that's a little bit annoying, but it also needs to be done.

**Comment by imesias** [comment]
@markuman :joy: Thanks, no worries. Appreciate the guidance on this as I'm not familiar with the process.

**Comment by imesias** [comment]
hmm, seems like the policy may not have been affected yet or perhaps I've missed something. The role still does not appear to have permission yet.

image

**Comment by gravesm** [comment]
This seems to be the result of needing to add the `cluster-pg:*` resource type to the permissions. I tried doing this locally, which gets further, but now it's failing for non-permission related reasons:
```
TASK [rds_cluster : Modify DB cluster parameter group] *************************

An exception occurred during task execution. To see the full traceback, use -vvv. The error was:
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateDBCluster operation: The parameter MasterUsername must be provided and must not be blank.
```

**Comment by imesias** [comment]
Yeah, ...it looks like it's calling create instead of modify. It seems I neglected the fact the cluster was previously renamed in the previous test. Hence it's trying to create a new cluster. I update shortly to...
```yaml
  - name: Modify DB cluster parameter group
    rds_cluster:
      id: "{{ new_cluster_id }}" # <------ 
      state: present
     db_cluster_parameter_group_name: "{{ new_db_parameter_group_name }}"
...
```

@gravesm will you add the `cluster-pg:*` resource type to the permissions in the terminator repo in the meanwhile? Or should I quickly open another PR?

Kind Regards,

**Comment by imesias** [comment]
@gravesm Sure,  no worries, will have a look  as soon as I am able to :-)

**Comment by imesias** [comment]
@gravesm Thanks for the assist and update. Much appreciated. @alinabuzachis @markuman integ tests are now passing.

**Review by markuman — APPROVED** [review]

**Pull request merged**
