### PR TITLE
Additional 'base' helper classes

### PR DESCRIPTION
**Pull request by tremble**
Depends-On: https://github.com/ansible-collections/community.aws/pull/984

##### SUMMARY

Working on #944 and some additional modules, I want to add support for --diff.  The API for NetworkFirewall also has some *interesting* requirements due to its use of opportunistic locking.

These classes provide the initial framework I'm using for this.  Once I've got the modules themselves landed I'll get unit tests for these classes written.  Note: some of this code currently overlaps with code currently available in amazon.aws, I want to prove things out here in community.aws before migrating them over to amazon.aws

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugin/module_utils/base.py

##### ADDITIONAL INFORMATION

Dependent PRs:
- #944 
- (More to follow)

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
retry

**Comment by tremble** [comment]
recheck

**Comment by markuman** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
We have a number of flaky integration tests, because this PR doesn't have any modules it's triggering the full test suite.  To work around this I've merged #974 into #944.  Both have been approved on their own.

**Pull request closed without merging**
