### PR TITLE
sns_topic: Loop through defaultHealthyRetryPolicy attributes and cast them as integers

### LINKED ISSUE #713: sns_topic: Integer parameters within defaultHealthyRetryPolicy are not converted from strings
### Summary

It's a curious issue that if you need to store variables for a module in a dict then when you pass them over to the module they will always be a string. (See example below.)

There doesn't seem to be any sane way to pass a true integer to the module in this case. Which leaves the only way around this as having the module itself ensure the values passed are cast as integers before they are sent to the AWS API. Given we know the API is fussy and we haven't seen anything like this with other modules, I'm assuming the "usual" behaviour for these AWS modules is to cast integers as there's no way to guarantee Ansible/jinja will send a true integer to the module. This module should do this too.

~~We've patched this module locally and it now works for us, I'll provide a PR tomorrow with our working changes.~~ PR provided! #716 

### Issue Type

Bug Report

### Component Name

sns_topic

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
  jinja version = 2.10
  libyaml = True

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
# /usr/local/lib/python3.7/dist-packages/ansible_collections
Collection                    Version
----------------------------- -------
amazon.aws                    1.5.0  
ansible.netcommon             2.1.0  
ansible.posix                 1.2.0  
ansible.utils                 2.2.0  
ansible.windows               1.6.0  
arista.eos                    2.1.2  
awx.awx                       19.2.0 
azure.azcollection            1.7.0  
check_point.mgmt              2.0.0  
chocolatey.chocolatey         1.1.0  
cisco.aci                     2.0.0  
cisco.asa                     2.0.2  
cisco.intersight              1.0.15 
cisco.ios                     2.2.0  
cisco.iosxr                   2.2.0  
cisco.meraki                  2.4.0  
cisco.mso                     1.2.0  
cisco.nso                     1.0.3  
cisco.nxos                    2.3.0  
cisco.ucs                     1.6.0  
cloudscale_ch.cloud           2.2.0  
community.aws                 1.5.0  
community.azure               1.0.0  
community.crypto              1.7.0  
community.digitalocean        1.5.1  
community.docker              1.7.0  
community.fortios             1.0.0  
community.general             3.2.0  
community.google              1.0.0  
community.grafana             1.2.1  
community.hashi_vault         1.1.3  
community.hrobot              1.1.1  
community.kubernetes          1.2.1  
community.kubevirt            1.0.0  
community.libvirt             1.0.1  
community.mongodb             1.2.1  
community.mysql               2.1.0  
community.network             3.0.0  
community.okd                 1.1.2  
community.postgresql          1.3.0  
community.proxysql            1.0.0  
community.rabbitmq            1.0.3  
community.routeros            1.1.0  
community.skydive             1.0.0  
community.sops                1.0.6  
community.vmware              1.10.0 
community.windows             1.4.0  
community.zabbix              1.3.0  
containers.podman             1.6.1  
cyberark.conjur               1.1.0  
cyberark.pas                  1.0.7  
dellemc.enterprise_sonic      1.1.0  
dellemc.openmanage            3.4.0  
dellemc.os10                  1.1.1  
dellemc.os6                   1.0.7  
dellemc.os9                   1.0.4  
f5networks.f5_modules         1.9.1  
fortinet.fortimanager         2.0.3  
fortinet.fortios              2.0.2  
frr.frr                       1.0.3  
gluster.gluster               1.0.1  
google.cloud                  1.0.2  
hetzner.hcloud                1.4.3  
hpe.nimble                    1.1.3  
ibm.qradar                    1.0.3  
infinidat.infinibox           1.2.4  
inspur.sm                     1.2.0  
junipernetworks.junos         2.2.0  
kubernetes.core               1.2.1  
mellanox.onyx                 1.0.0  
netapp.aws                    21.2.0 
netapp.azure                  21.7.0 
netapp.cloudmanager           21.7.0 
netapp.elementsw              21.6.1 
netapp.ontap                  21.7.0 
netapp.um_info                21.6.0 
netapp_eseries.santricity     1.2.12 
netbox.netbox                 3.1.1  
ngine_io.cloudstack           2.1.0  
ngine_io.exoscale             1.0.0  
ngine_io.vultr                1.1.0  
openstack.cloud               1.4.0  
openvswitch.openvswitch       2.0.0  
ovirt.ovirt                   1.5.0  
purestorage.flasharray        1.8.0  
purestorage.flashblade        1.6.0  
sensu.sensu_go                1.11.1 
servicenow.servicenow         1.0.6  
splunk.es                     1.0.2  
t_systems_mms.icinga_director 1.17.0 
theforeman.foreman            2.1.0  
vyos.vyos                     2.3.0  
wti.remote                    1.0.1  

```

### AWS SDK versions

```console (paste below)
$ pip3 show boto boto3 botocore
Name: boto
Version: 2.44.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.17.98
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: jmespath, botocore, s3transfer
Required-by: 
---
Name: botocore
Version: 1.21.40
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: python-dateutil, jmespath, urllib3
Required-by: s3transfer, boto3, awscli

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Debian Buster

### Steps to Reproduce

If my playbook looks like this - note particularly the vars, the SNS vars nested neatly into a dict for readability:

```yaml
---
- hosts: localhost
  tasks:
    - include: sns.yml
      vars:
        aws_sns:
          name: "alarms" # Name of the alarm.
          display_name: "" # Display name for the topic, for when the topic is owned by this AWS account.
          delivery_policy_default_healthy_retry_policy_min_delay_target: 20
          delivery_policy_default_healthy_retry_policy_max_delay_target: 20
          delivery_policy_default_healthy_retry_policy_num_retries: 3
          delivery_policy_default_healthy_retry_policy_backoff_function: "linear"
          delivery_policy_disable_subscription_overrides: false
          subscriptions:
            - endpoint: "alerts@example.com"
              protocol: "email"

```

And my role task looks like this in `sns.yml`:

```yaml
- name: Create SNS topic.
  community.aws.sns_topic:
    name: "{{ aws_sns.name }}"
    state: present
    display_name: "{{ aws_sns.display_name }}"
    delivery_policy:
      http:
        defaultHealthyRetryPolicy:
          minDelayTarget: "{{ aws_sns.delivery_policy_default_healthy_retry_policy_min_delay_target | int }}" 
          maxDelayTarget: "{{ aws_sns.delivery_policy_default_healthy_retry_policy_max_delay_target | int }}" 
          numRetries: "{{ aws_sns.delivery_policy_default_healthy_retry_policy_num_retries | int }}" 
          backoffFunction: "{{ aws_sns.delivery_policy_default_healthy_retry_policy_backoff_function }}"
        disableSubscriptionOverrides: "{{ aws_sns.delivery_policy_disable_subscription_overrides }}"
    subscriptions:
      "{{ aws_sns.subscriptions }}"
```

There's nothing wrong with that, we're even casting it as an int with jinja to try and be doubly sure, but it will still fail with this:

`"msg": "Couldn't set topic delivery policy: An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: DeliveryPolicy: http.defaultHealthyRetryPolicy.minDelayTarget type mismatch, expecting integer, received a string"`

### Expected Results

I expect the integers passed in the `aws_sns` dict to be respected as integers and passed as integers to the AWS API.

### Actual Results

`"msg": "Couldn't set topic delivery policy: An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: DeliveryPolicy: http.defaultHealthyRetryPolicy.minDelayTarget type mismatch, expecting integer, received a string"`

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by gregharvey**
##### SUMMARY

This is a simple patch that intercepts the `defaultHealthyRetryPolicy` attributes just before they are sent to the AWS API and ensures they are cast as integers, otherwise you get type errors if you try and set those attributes via a role in a dict (due to known limitations of jinja they get cast as strings by Ansible).

Fixes #713

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

sns_topic

##### ADDITIONAL INFORMATION

Because the AWS documentation for the `create-topic` method is virtually non-existent we've had to guess the attributes based on the UI, but as far as we can tell every attribute should be an integer within the `defaultHealthyRetryPolicy` dict *except* for `backoffFunction`, so we simply loop through the provided attributes casting as integer if it is *not* that attribute. Similarly, we have hard-coded the `http` key in the dict because, again as far as we can tell and without any real docs, there simply is no other option, so this is safe to do.

```paste below
BEFORE
======

TASK [aws/aws_sns : Create an SNS topic and subscription.] *********************
task path: /home/controller/ce-provision/roles/aws/aws_sns/tasks/main.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.aws.sns_topic_payload_f1uqbdm9/ansible_community.aws.sns_topic_payload.zip/ansible_collections/community/aws/plugins/modules/sns_topic.py", line 346, in _set_topic_attrs
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: DeliveryPolicy: http.defaultHealthyRetryPolicy.minDelayTarget type mismatch, expecting integer, received a string
fatal: [localhost]: FAILED! => {
    "boto3_version": "1.17.98",
    "botocore_version": "1.20.98",
    "changed": false,
    "error": {
        "code": "InvalidParameter",
        "message": "Invalid parameter: DeliveryPolicy: http.defaultHealthyRetryPolicy.minDelayTarget type mismatch, expecting integer, received a string",
        "type": "Sender"
    },
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "delivery_policy": {
                "http": {
                    "defaultHealthyRetryPolicy": {
                        "backoffFunction": "linear",
                        "maxDelayTarget": "20",
                        "minDelayTarget": "20",
                        "numMaxDelayRetries": "0",
                        "numMinDelayRetries": "0",
                        "numNoDelayRetries": "0",
                        "numRetries": "3"
                    },
                    "disableSubscriptionOverrides": false
                }
            },
            "display_name": "",
            "ec2_url": null,
            "name": "Notify-CodeEnigma-Pushover",
            "policy": null,
            "profile": null,
            "purge_subscriptions": true,
            "region": null,
            "security_token": null,
            "state": "present",
            "subscriptions": [
                {
                    "endpoint": "alert@example.com",
                    "protocol": "email"
                }
            ],
            "validate_certs": true
        }
    },
    "msg": "Couldn't set topic delivery policy: An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: DeliveryPolicy: http.defaultHealthyRetryPolicy.minDelayTarget type mismatch, expecting integer, received a string",
    "response_metadata": {
        "http_headers": {
            "content-length": "379",
            "content-type": "text/xml",
            "date": "Mon, 13 Sep 2021 12:54:00 GMT",
            "x-amzn-requestid": "264bf1a5-a080-5d81-84ae-a81ceca899d3"
        },
        "http_status_code": 400,
        "request_id": "264bf1a5-a080-5d81-84ae-a81ceca899d3",
        "retry_attempts": 0
    }
}


AFTER
=====

TASK [aws/aws_sns : Create an SNS topic and subscription.] *********************
task path: /home/controller/ce-provision/roles/aws/aws_sns/tasks/main.yml:2
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "delivery_policy": {
                "http": {
                    "defaultHealthyRetryPolicy": {
                        "backoffFunction": "linear",
                        "maxDelayTarget": 20,
                        "minDelayTarget": 20,
                        "numMaxDelayRetries": 0,
                        "numMinDelayRetries": 0,
                        "numNoDelayRetries": 0,
                        "numRetries": 3
                    },
                    "disableSubscriptionOverrides": false
                }
            },
            "display_name": "",
            "ec2_url": null,
            "name": "Notify-CodeEnigma-Pushover",
            "policy": null,
            "profile": null,
            "purge_subscriptions": true,
            "region": null,
            "security_token": null,
            "state": "present",
            "subscriptions": [
                {
                    "endpoint": "alert@example.com",
                    "protocol": "email"
                }
            ],
            "topic_type": "standard",
            "validate_certs": true
        }
    },
    "sns_arn": "arn:aws:sns:eu-west-1:XXXXXXXXXXXXXXXXX:Notify-CodeEnigma-Pushover",
    "sns_topic": {
        "attributes_set": [
            "delivery_policy"
        ],
        "check_mode": false,
        "delivery_policy": "{\"http\":{\"defaultHealthyRetryPolicy\":{\"minDelayTarget\":20,\"maxDelayTarget\":20,\"numRetries\":3,\"numMaxDelayRetries\":0,\"numNoDelayRetries\":0,\"numMinDelayRetries\":0,\"backoffFunction\":\"linear\"},\"disableSubscriptionOverrides\":false}}",
        "display_name": "",
        "name": "Notify-CodeEnigma-Pushover",
        "owner": "XXXXXXXXXXXXXXXXX",
        "policy": "{\"Version\":\"2008-10-17\",\"Id\":\"__default_policy_ID\",\"Statement\":[{\"Sid\":\"__default_statement_ID\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Action\":[\"SNS:GetTopicAttributes\",\"SNS:SetTopicAttributes\",\"SNS:AddPermission\",\"SNS:RemovePermission\",\"SNS:DeleteTopic\",\"SNS:Subscribe\",\"SNS:ListSubscriptionsByTopic\",\"SNS:Publish\",\"SNS:Receive\"],\"Resource\":\"arn:aws:sns:eu-west-1:XXXXXXXXXXXXXXXXX:Notify-CodeEnigma-Pushover\",\"Condition\":{\"StringEquals\":{\"AWS:SourceOwner\":\"XXXXXXXXXXXXXXXXX\"}}}]}",
        "state": "present",
        "subscriptions": [
            {
                "endpoint": "alert@example.com",
                "owner": "XXXXXXXXXXXXXXXXX",
                "protocol": "email",
                "subscription_arn": "arn:aws:sns:eu-west-1:XXXXXXXXXXXXXXXXX:Notify-CodeEnigma-Pushover:a00d4a62-48e5-4a46-a3bd-913e64c79a9a",
                "topic_arn": "arn:aws:sns:eu-west-1:XXXXXXXXXXXXXXXXX:Notify-CodeEnigma-Pushover"
            }
        ],
        "subscriptions_added": [],
        "subscriptions_confirmed": "1",
        "subscriptions_deleted": "0",
        "subscriptions_existing": [],
        "subscriptions_new": [
            {
                "endpoint": "alert@example.com",
                "protocol": "email"
            }
        ],
        "subscriptions_pending": "0",
        "subscriptions_purge": true,
        "topic_arn": "arn:aws:sns:eu-west-1:XXXXXXXXXXXXXXXXX:Notify-CodeEnigma-Pushover",
        "topic_created": false,
        "topic_deleted": false,
        "topic_type": "standard"
    }
}
```

### CODE REVIEW

**Comment by gregharvey** [comment]
Oops, indentations. I'm from a PHP background, I forgot to check if Python has different standards. :smiley: 
Hopefully tests will be happier this time.

**Review by alinabuzachis — COMMENTED** [review]
@gregharvey Thank you for taking time to work on this. Could you please add a changelog fragment https://cn-ansibledoc.readthedocs.io/zh_CN/latest/community/development_process.html#creating-a-changelog-fragment?

**Comment by gregharvey** [comment]
@alinabuzachis You're welcome, done - hope I did it right?

**Review by tremble — CHANGES_REQUESTED** [review]
Hi @gregharvey,

Thanks for taking the time to contribute this fix.  I tried updating our integration tests to catch this bug in future.  Unfortunately, it looks like your approach results in problems with idempotency: because during the comparison the value is still a string, it sees a change from an integer (in the existing policy) to a string (in the new policy) and always returns "changed" if someone uses strings instead of integers in the policy.  It would also throw exceptions if someone did something silly like passing `"notanumber"` instead of an integer, or simply didn't pass `defaultHealthyRetryPolicy`.

Rather than updating the value and throwing an ugly exception if someone tried to pass something other than a number it's better to properly define the delivery_policy option so that rather than it just being a free-form dictionary (associative array) we define what we shape we expect the dictionary to have.

Since this then involves updating the docs (which can be downright tedious), I've opened #739 which hopefully fixes your issue, as well as significantly improves the documentation.

**Comment by tremble** [comment]
Hi @gregharvey,

I very much appreciate that you took the time to contribute a fix here.

#739 has now been merged and should fix your issue.  It should be available in the collection whenever the next release occurs.


Mark

**Comment by gregharvey** [comment]
That looks like it'll work well, yes, thank you! :-)

**Pull request closed without merging**
