### PR TITLE
aws_ssm connection: add SSE encryption parameters.

### PR DESCRIPTION
**Pull request by fh-maxime-froment**
##### SUMMARY
Add the following parameters to aws_ssm.py connection plugin:
* ansible_aws_ssm_bucket_sse_mode
* ansible_aws_ssm_bucket_sse_kms_key_id

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
aws_ssm connection plugin

##### ADDITIONAL INFORMATION
This allows the connection plugin to work when encryption parameters are required for uploads on the file transfer bucket by policy / SCP (see [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingServerSideEncryption.html) for an example).

### CODE REVIEW

**Comment by jillr** [comment]
Thanks very much @fh-maxime-froment!  Would you be able to add some examples to the plugin showing how to use the new options?
 
I took a quick pass a some integration tests after we talked on irc today @briantist, I do think that all the necessary IAM permissions should be there.  I thought that this should cover it but I've definitely missed a step.  I don't have a ton of experience using SSM though so maybe something will stand out that I overlooked?

```
diff --git a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/main.yml b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/main.yml
index 2b1cc70..255e656 100644
--- a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/main.yml
+++ b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/main.yml
@@ -99,6 +99,12 @@
       wait_for_connection:
         delay: 360
 
+    - name: create a key
+      aws_kms:
+        alias: '{{ resource_prefix }}-kms'
+        tags:
+          ansible-test: '{{ resource_prefix }}'
+
     - name: Create S3 bucket
       s3_bucket:
         name: "{{resource_prefix}}-aws-ssm-s3"
diff --git a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2 b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
index 1788a9a..9ff8bfb 100644
--- a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
+++ b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
@@ -24,6 +24,8 @@ ansible_aws_ssm_bucket_name={{s3_output.name}}
 ansible_aws_ssm_plugin=/usr/local/sessionmanagerplugin/bin/session-manager-plugin
 ansible_python_interpreter=/usr/bin/env python
 local_tmp=/tmp/ansible-local-
+ansible_aws_ssm_bucket_sse_mode='aws:kms'
+ansible_aws_ssm_bucket_sse_kms_key_id={{ resource_prefix }}-kms
 
 # support tests that target testhost
 [testhost:children]
diff --git a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_teardown/tasks/main.yml b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_teardown/tasks/main.yml
index d9d174a..744fa26 100644
--- a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_teardown/tasks/main.yml
+++ b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_teardown/tasks/main.yml
@@ -78,6 +78,11 @@
       ignore_errors: yes
       when: iam_role_vars_file.stat.exists == true
 
+    - name: Delete the KMS key
+      aws_kms:
+        state: absent
+        alias: '{{ resource_prefix }}-kms'
+
     - name: Delete AWS keys environement
       file:
         path: "{{playbook_dir}}/aws-env-vars.sh"
```

That gets me a failure on the ping test, however the console shows that the key is created:
```
TASK [wait_for_connection] *****************************************************
task path: /root/ansible_collections/community/aws/tests/output/.tmp/integration/connection_aws_ssm-wr6uf5ih-ÅÑŚÌβŁÈ/tests/integration/targets/connection/test_connection.yml:12
fatal: [linux_i-0276941539bac81a1]: FAILED! => {
    "changed": false,
    "elapsed": 601,
    "msg": "timed out waiting for ping module test: An error occurred (KMS.NotFoundException) when calling the PutObject operation: Invalid keyId ansible-test-11838785-zim-kms"
}
```

**Comment by fh-maxime-froment** [comment]
Thanks a lot @jillr and @briantist !

Concerning the integration test: I believe that the KMS key id input should either be an ID or an alias prefixed with `alias/`.

Could you try with this instead?

> ```diff
> diff --git a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2 b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
> index 1788a9a..9ff8bfb 100644
> --- a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
> +++ b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
> @@ -24,6 +24,8 @@ ansible_aws_ssm_bucket_name={{s3_output.name}}
>  ansible_aws_ssm_plugin=/usr/local/sessionmanagerplugin/bin/session-manager-plugin
>  ansible_python_interpreter=/usr/bin/env python
>  local_tmp=/tmp/ansible-local-
> +ansible_aws_ssm_bucket_sse_mode='aws:kms'
> +ansible_aws_ssm_bucket_sse_kms_key_id=alias/{{ resource_prefix }}-kms
>  
>  # support tests that target testhost
>  [testhost:children]
> ```

**Comment by briantist** [comment]
> Thanks a lot @jillr and @briantist !
> 
> Concerning the integration test: besides the issue mentioned above by @briantist, I believe that the KMS key id input should either be an ID or an alias prefixed with `alias/`.
> 
> Could you try with this instead?

<details>

> > ```diff
> > diff --git a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2 b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
> > index 1788a9a..9ff8bfb 100644
> > --- a/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
> > +++ b/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/templates/inventory-combined.aws_ssm.j2
> > @@ -24,6 +24,8 @@ ansible_aws_ssm_bucket_name={{s3_output.name}}
> >  ansible_aws_ssm_plugin=/usr/local/sessionmanagerplugin/bin/session-manager-plugin
> >  ansible_python_interpreter=/usr/bin/env python
> >  local_tmp=/tmp/ansible-local-
> > +ansible_aws_ssm_bucket_sse_mode='aws:kms'
> > +ansible_aws_ssm_bucket_sse_kms_key_id=alias/{{ resource_prefix }}-kms
> >  
> >  # support tests that target testhost
> >  [testhost:children]
> > ```

</details>

> For a newly created bucket, it may still not work because of the issue mentioned by @briantist. Besides keeping the bucket persistent, another way to address it is to specify the regional endpoint when getting the S3 client, e.g.

<details>

> > ```diff
> > diff --git a/plugins/connection/aws_ssm.py b/plugins/connection/aws_ssm.py
> > index 1576512..b6e97cc 100644
> > --- a/plugins/connection/aws_ssm.py
> > +++ b/plugins/connection/aws_ssm.py
> > @@ -555,6 +555,7 @@ class Connection(ConnectionBase):
> >  
> >          client = session.client(
> >              service,
> > +            endpoint_url='https://s3.%s.amazonaws.com' % (region_name) if service == 's3' and region_name else None,
> >              config=Config(signature_version="s3v4")
> >          )
> >          return client
> > ```

</details>

> But that's a bit of scope for this PR and should probably be made optional as the global url otherwise returned by `client.generate_presigned_url` works in the general case.

I'll apply the patches mentioned from both of you and get that committed.

**Comment by jillr** [comment]
@briantist The [test splitter](https://github.com/ansible/ansible-zuul-jobs/tree/master/roles/ansible-test-splitter) job looks at which jobs are affected by what's in a git diff and dynamically divides them up in to test groups that can be run concurrently.  Searching for `targets_to_test` in https://fa56735c863c8b38bd5d-0ebe257bffad4793733d3627e560b2c6.ssl.cf1.rackcdn.com/763/b7976952cd5fa7b5165904718a16cf8fd8f043e1/check/ansible-test-splitter/c023be5/job-output.txt should get you to the right section.  For some reason though this one didn't get parsed correctly.  If the retry I've just kicked off doesn't work I'll ask our current CI vanguard to take a look at the job on Monday (Red Hat has a company-wide shutdown on Friday so unfortunately we'll all be offline).

A persistent bucket might work; @mattclay do you have any objections to this idea?  tl;dr: An encrypted S3 bucket can take up to 24 hours before the pre-signed URL works correctly.  So we could create an encrypted bucket that the terminator empties of files but otherwise ignores to be used for tests that need SSE.

**Comment by mattclay** [comment]
@jillr I don't see any issues with having a permanent bucket that is emptied regularly while leaving the bucket itself, as long as we make sure versioning is either disabled or that all versions of objects are removed.

**Comment by briantist** [comment]
tried to install the RPM on Fedors per @tremble 's suggestion. Now getting this error:

>  "msg": "Failed to validate GPG signature for session-manager-plugin-1.2.279.0-1.x86_64"

Not really sure how to fix that though 😕

**Comment by tremble** [comment]
Looks like redhat.yml needs the GPG key imported.  I'd recommend adding the key to the test https://docs.aws.amazon.com/systems-manager/latest/userguide/verify-agent-signature.html includes how to do this with RPM (as well as manually)

The current failure looks to be the length of the role name being too long, https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/main.yml#L50 it should be possible to use "tiny_prefix" instead of "resource_prefix" (but might need updating in other places too.

**Comment by briantist** [comment]
> Looks like redhat.yml needs the GPG key imported. I'd recommend adding the key to the test https://docs.aws.amazon.com/systems-manager/latest/userguide/verify-agent-signature.html includes how to do this with RPM (as well as manually)

I just skipped the key check.. I don't know where I'd add the key or what to do with it. This part of the tests isn't really part of this PR, it was already in place.

> The current failure looks to be the length of the role name being too long, https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/main.yml#L50 it should be possible to use "tiny_prefix" instead of "resource_prefix" (but might need updating in other places too.

alright, I'm trying that then... at this point we're really spinning our wheels here trying to make the existing tests work; none of this is related to the change in this PR, the tests were I guess disabled for so long that they've accumulated lots of breakage.

Not being able to run them locally makes this a painfully slow whack-a-mole process. If we hit more errors like this we'd really appreciate some help in moving past this point.

**Comment by briantist** [comment]
ok so we got to the point where it's trying to use the ssm connection in the tests, and it just never works. `wait_for_connection` times out eventually, it looks like there's tons of AccessDenied errors. I need maintainer help here, I don't know the reason.

> @jillr I don't see any issues with having a permanent bucket that is emptied regularly while leaving the bucket itself, as long as we make sure versioning is either disabled or that all versions of objects are removed.

Was this ever created? Could it be related?

**Comment by jillr** [comment]
@briantist The bucket hasn't yet been created yet, I have to create some terminator rules to go with it.  I'm working on getting more people able o help with the collection maintenance on but I'm still a bottleneck on the terminator.  :(

I tried to work on this a bit today but I can't get the tests to run locally.  There is definitely test breakage here that far exceeds the scope of this PR.  In this case we should manually verify this PR by running a set of Ansible tasks that check the functionally of the new feature (using the new integration tests as the basis) and turn off the test suite again until we can get the tests updated under their own bug report.

@alinabuzachis Would you have time to help do verification of this PR this week?

**Comment by briantist** [comment]
> @briantist The bucket hasn't yet been created yet, I have to create some terminator rules to go with it. I'm working on getting more people able to* help with the collection maintenance on but I'm still a bottleneck on the terminator. :(
> 
> I tried to work on this a bit today but I can't get the tests to run locally. There is definitely test breakage here that far exceeds the scope of this PR. In this case we should manually verify this PR by running a set of Ansible tasks that check the functionally of the new feature (using the new integration tests as the basis) and turn off the test suite again until we can get the tests updated under their own bug report.
> 
> @alinabuzachis Would you have time to help do verification of this PR this week?

Thank you @jillr , much appreciated! Even running the tests locally/outside CI will require the ~24hour baked-in bucket (I think), so that'd probably be the first thing to do.

**Comment by jillr** [comment]
We have a new bucket called `ssm-encrypted-test-bucket` that the terminator has been updated to ignore (but remove objects from).  It should be encryption enabled in the next several hours, hopefully.

**Comment by briantist** [comment]
> We have a new bucket called `ssm-encrypted-test-bucket` that the terminator has been updated to ignore (but remove objects from). It should be encryption enabled in the next several hours, hopefully.

@jillr I've updated the tests to stop creating an S3 bucket and to instead use the one that already exists (https://github.com/ansible-collections/community.aws/pull/763/commits/532ccd69b1a9e5b70e30b86e624cf9dd3a6f8478).

But still seeing AccessDenied errors when the tests try to execute; I can't tell where to fix that though.

**Comment by alinabuzachis** [comment]
I couldn't get these tests running locally without re-adding `needs/target/connection` and `needs/root`. @tremble Why can we get rid of these? I'm just trying to understand what's missing in my setup. 

Apart of that, using another S3 encrypted bucket, the PR seems to work correctly. I ran the integration tests and also tried to check any change in the S3 bucket using the console @jillr 

I guess there is a problem with bucket permissions @briantist. Since @jillr is now on PTO, when they will come back (next week) will set it up.

**Comment by alinabuzachis** [comment]
recheck

**Comment by jillr** [comment]
@briantist I've disabled these tests in CI. We've manually tested the plugin itself and are confident that the actual code here is good.  Once the merge conflict is resolved (the result of me disabling the tests, my apologies) I'm happy to merge this PR.  

@fh-maxime-froment I appreciate the patience you have given us, and for adding this feature!

**Review by jillr — APPROVED** [review]

**Comment by briantist** [comment]
@jillr thanks a lot! conflict has been resolved

**Comment by fh-maxime-froment** [comment]
@jillr @briantist @tremble @alinabuzachis Thank you all so much for following up on testing this PR!

**Comment by briantist** [comment]
Since `2.1.0` is already released, I updated the `version_added` field to `2.2.0` in https://github.com/ansible-collections/community.aws/pull/763/commits/4fd084af104e5723eb8925ea9494449f2762ab30. If this should be a different value let me know. 
(note: your `galaxy.yml` still says `2.1.0`; not sure how you all prefer to handle it but I like to bump that version to the next expected release after a new version is released)

**Review by markuman — APPROVED** [review]

**Pull request merged**
