### PR TITLE
support scan_on_push for ecs_ecr

### LINKED ISSUE #247: ecr option scan_on_push
##### SUMMARY
ecr module does not support `--image-scanning-configuration` option.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ecs_ecr

### PR DESCRIPTION
**Pull request by markuman**
##### SUMMARY
Fixed #247 

Add support for `scan_on_push` for `ecs_ecr`.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
ecs_ecr

##### ADDITIONAL INFORMATION

```paste below
   - name: create ecr registries
      community.aws.ecs_ecr:
        name: "mbtest123"
        scan_on_push: yes
        lifecycle_policy:
          rules:
            - rulePriority: 1
              description: keep only last 60 images
              selection:
                tagStatus: any
                countType: imageCountMoreThan
                countNumber: 60
              action:
                type: expire

```

### CODE REVIEW

**Comment by markuman** [comment]
CI is failing due lack of permissions...

```
 ClientError: An error occurred (AccessDeniedException) when calling the PutImageScanningConfiguration operation: User: arn:aws:sts::966509639900:assumed-role/ansible-core-ci-test-prod/prod=shippable=ansible-collections=community.aws=812.22 is not authorized to perform: ecr:PutImageScanningConfiguration on resource: arn:aws:ecr:us-east-1:966509639900:repository/shippable-812-22-ecr
```

**Review by jillr — COMMENTED** [review]
Just a couple test requests, otherwise this looks pretty good, thanks.
Updated permissions have been deployed to CI.

**Comment by jillr** [comment]
@markuman can you please update the module to document that it requires botocore>=1.13.3 (that's when scanning support was added)?  I still need to figure out why the updated tests/integration/requirements.txt isn't installing.

**Comment by markuman** [comment]
> @markuman can you please update the module to document that it requires botocore>=1.13.3 (that's when scanning support was added)? I still need to figure out why the updated tests/integration/requirements.txt isn't installing.

@jillr done.  
Any findings related to the CI requirements issue?

**Comment by jillr** [comment]
Because botocore is specified in a few different requirements files - and more importantly, a constraints file that's a part of ansible-test, this is actually a bit more involved that just adding the new requirement to the collection.  test/lib/ansible_test/_data/requirements/constraints.txt is limiting what we can do with the requirement, I'm talking to mattclay about how we're going to fix this so that it doesn't impact any other collections that might be using botocore.  I will let you know as soon as we have something in place.

**Review by jillr — APPROVED** [review]
Thanks @markuman!

**Pull request merged**
