### PR TITLE
adjust booleans: use true/false

### PR DESCRIPTION
**Pull request by markuman**
Depends-On: https://github.com/ansible-collections/community.aws/pull/1423

##### SUMMARY

https://github.com/ansible-community/community-topics/issues/116

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by markuman** [comment]
the errors does not seem to be related to this PR

>     "msg": "Failed to enable AZ on load balancers: An error occurred (ValidationError) when calling the EnableAvailabilityZonesForLoadBalancer operation: You cannot enable Availability Zones for ELBs in a non default VPC",

and pip is failing

> ... core==1.20.40 because these package versions have conflicting dependencies.\nERROR: ResolutionImpossible

**Comment by markuman** [comment]
recheck

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
#1423 should fix the botocore/boto3 install issues

**Comment by markuman** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by markuman** [comment]
rate limit error, that throws an exception in an exception

```
botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeVpnGateways operation (reached max retries: 4): Request limit exceeded.

During handling of the above exception, another exception occurred:
```

**Comment by markuman** [comment]
recheck

**Comment by alinabuzachis** [comment]
> rate limit error, that throws an exception in an exception
> 
> ```
> botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeVpnGateways operation (reached max retries: 4): Request limit exceeded.
> 
> During handling of the above exception, another exception occurred:
> ```

Isn't this weird since  jittered_backoff(retries=10)) has this config inside the ec2_vpc_vpn module and describe_vpc_gateways has aws_retry=True?

**Comment by markuman** [comment]
> > rate limit error, that throws an exception in an exception
> > ```
> > botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeVpnGateways operation (reached max retries: 4): Request limit exceeded.
> > 
> > During handling of the above exception, another exception occurred:
> > ```
> 
> Isn't this weird since jittered_backoff(retries=10)) has this config inside the ec2_vpc_vpn module and describe_vpc_gateways has aws_retry=True?

yes, and it is constantly failing...

**Comment by markuman** [comment]
recheck

**Comment by markuman** [comment]
party!!

**Pull request merged**
