### PR TITLE
DNM: rds_instance/test: split up the test

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/976

First iteration, a lot of dup code. Do Not Merge

### CODE REVIEW

**Comment by tremble** [comment]
a) These tests are already running in parallel, unfortunately the "slow" part is the length of time it takes to stand up an RDS cluster

b) Last time I tried, <foo>_2 didn't work properly, even with the main module added to the aliases file it wouldn't trigger on changes to the module

**Comment by goneri** [comment]
> a) These tests are already running in parallel, unfortunately the "slow" part is the length of time it takes to stand up an RDS cluster

oh. ok. Thanks!

> b) Last time I tried, _2 didn't work properly, even with the main module added to the aliases file it wouldn't trigger on changes to the module

It should be better now because we can adjust https://github.com/ansible/ansible-zuul-jobs/blob/master/roles/ansible-test/tasks/ansible_test_changed.yaml to return all the target we want.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Pull request closed without merging**
