### PR TITLE
add links from README to collection dev guide

### LINKED ISSUE #120: Documentation request - how to test changes to this repo
##### SUMMARY

I want to write a PR for #115 .

Previously when this was part of the [main ansible repo](https://github.com/ansible/ansible/) I was able to follow [these instructions](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#environment-setup). But now those instructions no longer apply, because it's a different repo, with a different lifecycle.

The first place I looked was the top-level README for this repo.
Nope, that's not useful.

It tells me how to *install* the repo, from the remote server. I want to install from my local repo, how do I do that?

It links to the [using collections page](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html), which again only explains how to install a collection published on a remote server. Do I have to create my own Galaxy server just to test a one line change to this repo?

The top-level README of this repo links to the [dev guide for the main Ansible repo](https://docs.ansible.com/ansible/latest/community/index.html), which again is not relevant.
Do I need to clone the main ansible repo, and follow the those instructions? Or can I use any published version of Ansible installed with `pip install`?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

community.aws

##### ANSIBLE VERSION

```paste below
master branch
```

### PR DESCRIPTION
**Pull request by mdavis-xyz**
##### SUMMARY

Fixes #120 

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mdavis-xyz** [comment]
@jillr why was this closed?

The existing documentation is definitely inadequate.

For example, even if a user does manage to find [Developing Collections](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#testing-collections) and they try to run the first testing command to run sanity tests, the result is something with a lot of errors. And they're not errors about being unable to find an IAM credential.

Is that normal? Is that expected? Am I supposed to install other collections as a dependency of this one?

**Comment by mdavis-xyz** [comment]
Another issue that makes contributing hard, you cannot just clone the repo anywhere. It needs to be in `/path/to/somewhere/ansible/collections/ansible_collections/community/community.aws/`, otherwise the sanity tests won't run

```
> ERROR: The current working directory must be at or below:
> - an Ansible collection: {...}/ansible_collections/{namespace}/{collection}/
```

I have never seen any project that can't be run unless it's got a specifically named heirachy of parent directories before. This is not obvious to new developers. So it should be documented. Simply pointing to *the entire* Ansible dev guide is not sufficient. That's a million words long, and contains unrelated information like how to write a module from scratch, a collection from scratch etc.

**Comment by jillr** [comment]
@mdavis-xyz  The default branch for this repo was changed.  PRs were remapped to the new branch, but for some reason 2 PRs (this and one other) did not remap and were not caught by that automation.  So when we deleted `master` it was automatically closed inadvertently.  I'm reopening and manually remapping this PR.

**Comment by jillr** [comment]
@mdavis-xyz This PR just needs passing CI, based on the shippable errors it should just need a rebase on `main` and re-push to your branch.

**Comment by mdavis-xyz** [comment]
I've rebased, and now the CICD is still failing:

> Process install dependency map |ERROR! Collection artifact at 'community-aws-1.0.1-dev22.tar.gz' is not a valid tar file.

**Comment by jillr** [comment]
that one is on our side, I'll look into that - thanks @mdavis-xyz

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
