### PR TITLE
Migrate rds_instance* modules and tests

### PR DESCRIPTION
**Pull request by alinabuzachis**
Depends-On: https://github.com/ansible-collections/amazon.aws/pull/1011
Depends-On: https://github.com/ansible-collections/community.aws/pull/1480

Remove rds_instance* modules and tests
These modules have been migrated to `amazon.aws`
Update runtime.yml with redirects to that collection
Update ignore files

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@tremble So, merging first the corresponding promotion PR in amazon.aws would solve this, right?

```
writing output... [100%] index
[885](https://github.com/ansible-collections/community.aws/actions/runs/3053020927/jobs/4923115925#step:11:887)
  /home/runner/work/_temp/docsbuild/head/rst/collections/community/aws/rds_instance_info_module.rst:22: WARNING: undefined label: 'ansible_collections.amazon.aws.rds_instance_info_module'
[886](https://github.com/ansible-collections/community.aws/actions/runs/3053020927/jobs/4923115925#step:11:888)
  /home/runner/work/_temp/docsbuild/head/rst/collections/community/aws/rds_instance_module.rst:22: WARNING: undefined label: 'ansible_collections.amazon.aws.rds_instance_module'
[887](https://github.com/ansible-collections/community.aws/actions/runs/3053020927/jobs/4923115925#step:11:889)
  /home/runner/work/_temp/docsbuild/head/rst/collections/community/aws/rds_instance_snapshot_module.rst:22: WARNING: undefined label: 'ansible_collections.amazon.aws.rds_instance_snapshot_module'
```

**Comment by tremble** [comment]
> @tremble So, merging first the corresponding promotion PR in amazon.aws would solve this, right?

No, we need to merge the update to the workflow first.  Basically changes to the workflow aren't 'live' until we update the branch that we're merging into.

**Comment by alinabuzachis** [comment]
> No, we need to merge the update to the workflow first. Basically changes to the workflow aren't 'live' until we update the branch that we're merging into.

So, you're suggesting that we need a separate PR to update docs links for each module we migrate, right?

**Review by gravesm — APPROVED** [review]

**Review by abikouo — APPROVED** [review]
LGTM

**Review by tremble — APPROVED** [review]

**Pull request merged**
