### PR TITLE
Remove "missing credentials" tests

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

AWS Client creation is now done inside a helper module which is more thoroughly tested. Remove the extra tests from aws_api_gateway, ec2_asg, ec2_transit_gateway, lambda_policy, and rds_instance. They bring no significant value but do bump up the login failure count, which can result in the IPs getting temporarily black-listed

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

aws_api_gateway
ec2_asg
ec2_transit_gateway
lambda
lambda_policy
rds_instance

##### ADDITIONAL INFORMATION

https://github.com/ansible-collections/amazon.aws/blob/main/tests/integration/targets/module_utils_ec2/roles/connect_to_aws/tasks/main.yml

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by markuman** [comment]
imo the failing task is not  related to this pr

the idempotent task [L313](https://github.com/tremble/community.aws/blob/cleanup/cred_tests/tests/integration/targets/s3_lifecycle/tasks/main.yml#L313) still registers the value  from the previous task [L288](https://github.com/tremble/community.aws/blob/cleanup/cred_tests/tests/integration/targets/s3_lifecycle/tasks/main.yml#L288)

```
-                    "NoncurrentDays": 30,
+                    "NoncurrentDays": 300,

```

**Comment by tremble** [comment]
recheck

**Review by markuman — APPROVED** [review]

**Pull request merged**
