### PR TITLE
Add constraints and requirements for unit/integration tests

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Now that we state that we support specific minimum versions of the AWS SDKs, make sure we base our unit/integration tests against them such that modules need to explicitly test/request newer versions of the SDKs.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

tests/integration
tests/unit

##### ADDITIONAL INFORMATION

Depends-On: https://github.com/ansible-collections/amazon.aws/pull/461

see also: https://github.com/ansible/ansible-zuul-jobs/pull/991
see also: https://github.com/ansible-collections/amazon.aws/pull/404

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Pull request merged**
