### PR TITLE
Attempt to improve the stability of ec2_vpc_vgw and ec2_vpc_vpn

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

With the increased concurrency of tests we've started hitting 'The maximum number of mutating objects has been reached.'

Unfortunately AWS uses the same Error Code for 'Too much changing' as 'Too many VPNs/VGWs', so we need to tweak the retry class a little

fixes: #156 
fixes: #154 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_vpc_vgw
ec2_vpc_vpn

##### ADDITIONAL INFORMATION

See attached issues for example failures

### CODE REVIEW

**Comment by tremble** [comment]
Migration to wrapped clients has broken the unit tests, will need to dig into those to fix

**Comment by tremble** [comment]
Need to fix unit tests to cope with wrapped client

**Comment by jillr** [comment]
@tremble I noticed you took the WIP off this. What you have here looks good, were you still working on the unit tests?

**Comment by tremble** [comment]
@jillr Unit tests still need updating, I thought it was done and then realised that the unit tests weren't being run

**Comment by tremble** [comment]
@jillr ok.  Unit tests fixed.  (rolls eyes at how stupidly simple the fix was)

**Review by alinabuzachis — APPROVED** [review]
LGTM. Thank you. This also helped me dig deeper into how to use AWSRetry. :-)

**Comment by tremble** [comment]
Tests passing and approved.  Merging

**Pull request merged**
