### PR TITLE
ecs_service supports load balancer update

### PR DESCRIPTION
**Pull request by zhoufeng1989**
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ecs_service

##### ADDITIONAL INFORMATION

As [aws docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html) says, aws ecs service now supports load balancer update with `UpdateService` API if deploymentController type is ECS.
This pull request supports load balancer update.

```paste below

```

### CODE REVIEW

**Comment by markuman** [comment]
Oh, when did they introduce this? Until now, it's still not changeable via web gui (console)

**Comment by zhoufeng1989** [comment]
> Oh, when did they introduce this? Until now, it's still not changeable via web gui (console)

It seems that AWS start to support this March, 2022. 
Here is the related post: https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-ecs-service-api-updating-elastic-load-balancers-service-registries-tag-propagation-ecs-managed-tags/

**Comment by markuman** [comment]
@zhoufeng1989 there was a PR merge releated to `ecs_service`. Can you please [rebase](https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html) your PR?  
Since the ecs integration test is still broken, it helps to review and test this PR.

**Comment by zhoufeng1989** [comment]
@markuman PR has been rebased.

**Comment by markuman** [comment]
recheck

**Review by markuman — APPROVED** [review]

**Review by alinabuzachis — APPROVED** [review]

**Pull request merged**
