### PR TITLE
Bulk migration to AnsibleAWSModule

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Migrate to AnsibleAWSModule en masse
- Use AnsibleAWSModule instead of AnsibleModule
- Remove extra ec2_argument_spec calls
- Let AnsibleAWSModule handle missing Boto 3 libraries
- Use ec2.HAS_BOTO and ec2.HAS_BOTO3 for Boto 2 based modules
- Reorder imports and split into single lines (for cleaner followup PRs when more imports can be removed)

**Note:** I recommend reviewing each commit separately

Does *not* modify Boto connection creation as this is more likely to trigger unit-test breakage / issues / changes in behaviour.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/modules/aws_api_gateway.py
plugins/modules/aws_direct_connect_gateway.py
plugins/modules/aws_direct_connect_link_aggregation_group.py
plugins/modules/aws_kms_info.py
plugins/modules/aws_s3_bucket_info.py
plugins/modules/cloudfront_info.py
plugins/modules/cloudwatchlogs_log_group.py
plugins/modules/cloudwatchlogs_log_group_info.py
plugins/modules/data_pipeline.py
plugins/modules/dynamodb_table.py
plugins/modules/dynamodb_ttl.py
plugins/modules/ec2_ami_copy.py
plugins/modules/ec2_asg.py
plugins/modules/ec2_customer_gateway.py
plugins/modules/ec2_eip.py
plugins/modules/ec2_elb.py
plugins/modules/ec2_elb_info.py
plugins/modules/ec2_instance_info.py
plugins/modules/ec2_lc.py
plugins/modules/ec2_lc_find.py
plugins/modules/ec2_lc_info.py
plugins/modules/ec2_scaling_policy.py
plugins/modules/ec2_snapshot_copy.py
plugins/modules/ec2_vpc_egress_igw.py
plugins/modules/ec2_vpc_endpoint.py
plugins/modules/ec2_vpc_endpoint_info.py
plugins/modules/ec2_vpc_igw_info.py
plugins/modules/ec2_vpc_nat_gateway.py
plugins/modules/ec2_vpc_nat_gateway_info.py
plugins/modules/ec2_vpc_peer.py
plugins/modules/ec2_vpc_peering_info.py
plugins/modules/ec2_vpc_route_table_info.py
plugins/modules/ec2_vpc_vgw.py
plugins/modules/ec2_vpc_vgw_info.py
plugins/modules/ec2_win_password.py
plugins/modules/ecs_attribute.py
plugins/modules/ecs_cluster.py
plugins/modules/elasticache.py
plugins/modules/elasticache_parameter_group.py
plugins/modules/elasticache_snapshot.py
plugins/modules/elasticache_subnet_group.py
plugins/modules/elb_application_lb_info.py
plugins/modules/elb_classic_lb.py
plugins/modules/elb_instance.py
plugins/modules/elb_target.py
plugins/modules/elb_target_group_info.py
plugins/modules/execute_lambda.py
plugins/modules/iam.py
plugins/modules/iam_cert.py
plugins/modules/iam_managed_policy.py
plugins/modules/iam_mfa_device_info.py
plugins/modules/iam_server_certificate_info.py
plugins/modules/kinesis_stream.py
plugins/modules/lambda_alias.py
plugins/modules/lambda_event.py
plugins/modules/rds.py
plugins/modules/rds_param_group.py
plugins/modules/rds_subnet_group.py
plugins/modules/redshift.py
plugins/modules/redshift_subnet_group.py
plugins/modules/route53.py
plugins/modules/route53_health_check.py
plugins/modules/route53_info.py
plugins/modules/s3_logging.py
plugins/modules/s3_sync.py
plugins/modules/s3_website.py
plugins/modules/sts_session_token.py

### CODE REVIEW

**Comment by tremble** [comment]
First test set (pre-commit log) https://app.shippable.com/github/ansible-collections/community.aws/runs/519
EIP tests failed - the 'are there any EIPs in use' safety tiggered at the start of the tests (concurrency flake)

**Comment by tremble** [comment]
Second test run (post-commit log) https://app.shippable.com/github/ansible-collections/community.aws/runs/520/summary/console

The EIP tests were the only failures.  Of specific note, exactly 1 EIP test passed per run, and with manual restarts it was able to pass on each Python/Ansible combination.  This implies that the failure was the known EIP flake rather than a problem introduced by this change.

**Comment by tremble** [comment]
@jillr How would you feel about trying to get this one in prior to the 2.10 release?

**Comment by jillr** [comment]
> @jillr How would you feel about trying to get this one in prior to the 2.10 release?

*0 / 68 files viewed* 
@tremble  Maaaybe?  I'm not opposed to the PR, we'll see what I can do on time though.

**Pull request merged**
