### PR TITLE
Add platform to ecs service

### PR DESCRIPTION
**Pull request by duderamos**
##### SUMMARY

Closes: https://github.com/ansible-collections/community.aws/issues/136

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

ecs_service

### CODE REVIEW

**Comment by duderamos** [comment]
In order to address [this conversation](https://github.com/ansible-collections/community.aws/pull/151#r470999097), I removed the list of choices and added a reference to official documentation.

**Comment by markuman** [comment]
You need a changelog fragment and you add `version_added` to the documentation.

**Comment by duderamos** [comment]
Hey @markuman, thanks for your feedback. I added a changelog fragment, but I'm unsure about `you add version_added to the documentation` part. The module that I changed already has a `version_added` and I couldn't find an example from other recent PRs regarding this matter. Can you please clarify?

**Comment by duderamos** [comment]
Hey @tremble , could you check this for me please?

**Comment by jillr** [comment]
> The module that I changed already has a `version_added` and I couldn't find an example from other recent PRs regarding this matter. Can you please clarify?

`version_added` can also be added at the option level, to show which collection release it was added in.  You can see it in `ec2_vol` here:
https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/ec2_vol.py#L95-L107
We'll be releasing 1.4.0 in the next few days, so this would likely need to be 1.5.0

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
#340 looks like it still needs work.  Since this PR looks like it's ready to roll I'll merge it and deployment controller can be separately managed.

**Pull request merged**
