### PR TITLE
Fix passing an instance profile arn to ec2_launch_template

### PR DESCRIPTION
**Pull request by kepstin**
##### SUMMARY

If the string given on the iam_instance_profile looked like an arn, the
wrong structure format was being returned. boto3 expects a dict of the
format { arn: "{{ arn }}" } but the bare arn string was returned instead.

This fixes this error:
```
Couldn't create subsequent launch template version: Parameter validation failed:
Invalid type for parameter LaunchTemplateData.IamInstanceProfile, value: arn:aws:iam::[...]:instance-profile/[...], type: <class 'str'>, valid types: <class 'dict'>
```

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
community.aws.ec2_launch_template

### CODE REVIEW

**Review by markuman — APPROVED** [review]
LGTM

**Comment by tremble** [comment]
Hi @kepstin,

Thanks for the time you've taken to submit this PR.  Do you think you'd be able to update our integration tests to include the failure mode you were seeing?

We already have some tests which try to exercise the iam_instance_profile option.  I'm guessing they didn't go far enough:

https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/ec2_launch_template/playbooks/roles/ec2_launch_template/tasks/iam_instance_role.yml

**Comment by kepstin** [comment]
I don't really know about how the integration test setup works to be able to do that.

It looks like the current tests provide only a role name, and use the arn lookup functionality - to test the issue that i've been seeing, a test has to be added that instead provides an instance profile arn that matches the regex shown in https://github.com/ansible-collections/community.aws/blob/b056911288aa07981cd4b50d33bd8952582c35c2/plugins/modules/ec2_launch_template.py#L386

I assume this would require some setup in the test aws environment to ensure that an instance profile is available with a known fixed arn (or to determine the arn out of band and provide it).

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
@kepstin sorry it's taken a while.  I've added a changelog fragment and simple test.  I think we're ready to get this PR merged.

**Pull request merged**
