### PR TITLE
Add asg refresh and asg refresh info modules

### LINKED ISSUE #135: Autoscaling instance refresh API support
##### SUMMARY

AWS recently introduced "Instance refresh" feature in ASG. Using it is preferred way to update launch configuration in ASG

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_asg
##### ADDITIONAL INFORMATION

Deploying ASG from the client depends on internet connectivity and is not transactional. In the middle of deployment of ASG it can fail leaving ASG in unpredicted state. Using AWS infrastructure will add more stability in deployment (and probably will make it faster)

More about the feature: https://aws.amazon.com/blogs/compute/introducing-instance-refresh-for-ec2-auto-scaling/

Boto3 documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/autoscaling.html#AutoScaling.Client.start_instance_refresh

```yaml
- commutiny.aws.ec2_asg_instance_refresh:
    name: some-backend
```

### PR DESCRIPTION
**Pull request by danquixote**
##### SUMMARY
Fixes #135 
Resubmitting rebased-PR after initial review on #487 by @tremble .
Overview:
Adding the ec2_asg_instance_refresh and related *_info module. These modules are intended to be used together to start or cancel an EC2 AutoScaling Group (ASG) instance refresh, and then track the subsequent progress with the provided InstanceRefreshId. The *_info module can also be used to get multiple pages of refresh history using the NextToken.
Fixes #487

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
ec2_asg_instance_refresh
ec2_asg_instance_refreshes_info

##### ADDITIONAL INFORMATION

```

{
           'instance_refresh_id': 'string'
 }


 {
            'instance_refreshes': [
                    {
                        'instance_refresh_id': '6507a3e5-4950-4503-8978-e9f2636efc09',
                        'auto_scaling_group_name': 'ansible-test-hermes-63642726-asg',
                        'status': 'Cancelled',
                        'status_reason': 'Cancelled due to user request.',
                        'start_time': '2021-02-04T03:39:40+00:00',
                        'end_time': '2021-02-04T03:41:18+00:00',
                        'percentage_complete': 0,
                        'instances_to_update': 1
                    }
            ],
            'next_token': 'string'
        }


```

### CODE REVIEW

**Review by alinabuzachis — COMMENTED** [review]
@danquixote Thank you very much for working on this. It really is in Avery good shape. Could you please add `check_mode` for these modules and expand the tests (combine tasks running with and without `check_mode`)?

**Comment by mandar242** [comment]
Hi @danquixote, Thank you so much for contributing on this.

Would you be interested in continuing to work on it?

Also, while testing out your PR code, I accidentally pushed the fix for merge conflict to your branch, please revert the commit if you wish to do so (I'm also open to collaborating on this PR to take it to completion).

**Comment by jillr** [comment]
It would be great to have @danquixote's hard work here be merged.  @mandar242 would you be able to open a new PR based on this one (create a branch on your own fork of the repo, and open a PR from that) that preserves their commit history so we can get this over the finish line?

**Comment by alinabuzachis** [comment]
Closed because superseded by https://github.com/ansible-collections/community.aws/pull/973

**Pull request closed without merging**
