### PR TITLE
Remove ANSIBLE_METADATA

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Remove ANSIBLE_METADATA
https://github.com/ansible-collections/overview/issues/57

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
```
08:12     "error": {
08:12         "code": "InvalidConfigurationRequest", 
08:12         "message": "Stickiness type 'lb_cookie' is not supported for target groups with the UDP protocol", 
08:12         "type": "Sender"
08:12     }, 
```

**Comment by jillr** [comment]
Does this PR add any changes not covered in https://github.com/ansible-collections/community.aws/pull/70?

**Comment by Andersson007** [comment]
@jillr probably no:) difficult to check:) sorry for bothering

**Pull request closed without merging**
