### PR TITLE
feat: add wait and wait_timeout to mq_broker; closes #1879

### LINKED ISSUE #1879: mq_broker: add wait and wait_for parameters
### Summary

Add wait and wait_timeout parameters to wait for a specific state.
https://github.com/ansible-collections/community.aws/pull/1831#issuecomment-1582566844

### Issue Type

Feature Idea

### Component Name

mq_broker

### Additional Information

```yaml
  wait:
    description:
      - Specifies whether the module waits for the desired C(state).
    type: bool
  wait_timeout:
    description:
      - How long to wait (in seconds) for the broker to reach the desired state.
    default: 600
    type: int
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by alialkhalidi**
##### SUMMARY
add wait and wait_timeout to wait for broker desired state. This will be used instead of polling for broker desired state though a separate module, broker_info.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mq_broker

##### ADDITIONAL INFORMATION
```yaml
  wait:
    description:
      - Specifies whether the module waits for the desired C(state).
    type: bool
  wait_timeout:
    description:
      - How long to wait (in seconds) for the broker to reach the desired state.
    default: 900
    type: int
```

### CODE REVIEW

**Comment by alialkhalidi** [comment]
@alinabuzachis @markuman anything else needed here?

**Comment by alialkhalidi** [comment]
ready_for_review

**Comment by alialkhalidi** [comment]
recheck

**Comment by alialkhalidi** [comment]
@alinabuzachis @tremble rebased. can we finish this?

**Comment by alialkhalidi** [comment]
@alinabuzachis @tremble @markuman. can we finish this?

**Review by alinabuzachis — APPROVED** [review]
@alialkhalidi Sorry for the late reply. Can you please update version_added to 7.1.0? Other than that, LGTM! Thank you for working on this.

**Comment by alialkhalidi** [comment]
recheck

**Comment by alialkhalidi** [comment]
@alinabuzachis those failing tests are expected?

**Comment by markuman** [comment]
recheck

**Comment by alialkhalidi** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Pull request merged**
