### PR TITLE
ec2_instance: fix launch_template condition

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Fixes: ansible/ansible#51941

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/51941_ec2_instance.yml
plugins/modules/ec2_instance.py

### CODE REVIEW

**Comment by goneri** [comment]
Hi @Akasurde, is this something you are still working on?

**Review by markuman — APPROVED** [review]
LGTM

**Comment by tremble** [comment]
Needs a changelog and some integration tests

**Comment by markuman** [comment]
@Akasurde @jillr @goneri 

I hit the same error which is fixed in this PR `s/or/and not/`.

However, that's not sufficient to get it work.

First, it looks like you cannot overwrite launch template parameters using boto3. And while `ec2_instance` is setting several default values (_instance type, network interface, tag specification and block device mapping_), you will always get the error message   
`"Failed to create new EC2 instance: An error occurred (Unsupported) when calling the RunInstances operation: The requested configuration is currently not supported. Please check the documentation for supported configurations."`.

For example:  
origin module is passing  
```
{'BlockDeviceMappings': [], 'ClientToken': '37d405af374948e2bd427ff4a7a7fc04', 'InstanceType': 't2.micro', 'LaunchTemplate': {'LaunchTemplateName': 'ubuntu-20.04'}, 'MaxCount': 1, 'MinCount': 1, 'NetworkInterfaces': [{'DeviceIndex': 0, 'SubnetId': 'subnet-3e5fe743'}], 'TagSpecifications': [{'ResourceType': 'volume', 'Tags': [{'Key': 'Name', 'Value': 'lttest01'}]}, {'ResourceType': 'instance', 'Tags': [{'Key': 'Name', 'Value': 'lttest01'}]}]}
```

to run instance on playbook

```yml
    - name: test launchtemplate usage
      ec2_instance:
        wait: yes
        name: "{{ name }}"
        launch_template:
          name: ubuntu-20.04
        vpc_subnet_id: subnet-3e5fe743
```

With that patch, is runs smoothly

```diff
@@ -1273,16 +1262,17 @@ def build_run_instance_spec(params, ec2=None):
         MinCount=1,
     )
     # network parameters
-    spec['NetworkInterfaces'] = build_network_spec(params, ec2)
-    spec['BlockDeviceMappings'] = build_volume_spec(params)
-    spec.update(**build_top_level_options(params))
-    spec['TagSpecifications'] = build_instance_tags(params)
+    if not params.get('launch_template'):
+        spec['NetworkInterfaces'] = build_network_spec(params, ec2)
+        spec['BlockDeviceMappings'] = build_volume_spec(params)
+        spec['TagSpecifications'] = build_instance_tags(params)
+        # IAM profile
+        if params.get('instance_role'):
+            spec['IamInstanceProfile'] = dict(Arn=determine_iam_role(params.get('instance_role')))
+        spec['InstanceType'] = params['instance_type']
 
-    # IAM profile
-    if params.get('instance_role'):
-        spec['IamInstanceProfile'] = dict(Arn=determine_iam_role(params.get('instance_role')))
+    spec.update(**build_top_level_options(params))
 
-    spec['InstanceType'] = params['instance_type']
     return spec
```

But changes single parameter from the launch template is a necessary feature. The way to achieve it, is to describe the requested launch template and pass all parameters directly to `run_instance` and not request the launch template itself.  
That's a great task :)

**Comment by tremble** [comment]
@markuman Since you've already done some work on this, do you think you could create a fresh PR that we can get merged (changelog / integration tests / + bugfix) ?

**Comment by markuman** [comment]
I'm closing this PR because it's not active anymore and the module has moved to `amazon.aws` collection.  
But I've created an Issue there, imo with all related informations and links https://github.com/ansible-collections/amazon.aws/issues/451

**Pull request closed without merging**
