### PR TITLE
Fix introduced bug in elb_target_group_info

### PR DESCRIPTION
**Pull request by marknet15**
##### SUMMARY
Fix bug introduced here: https://github.com/ansible-collections/community.aws/pull/1001

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
elb_target_group_info

### CODE REVIEW

**Review by alinabuzachis — APPROVED** [review]

**Comment by marknet15** [comment]
@alinabuzachis @markuman would one of you be able to close these ?
https://github.com/ansible-collections/community.aws/pull/1006
https://github.com/ansible-collections/community.aws/pull/1005

With them closing would the patchback bot still raise the correct PRs for this one with the changes from the earlier PR ?

**Review by markuman — APPROVED** [review]

**Comment by marknet15** [comment]
regate

**Comment by markuman** [comment]
I think we must wait until this is fixed

> /bin/sh: line 1: /usr/bin/ansible-galaxy: No such file or directory

**Comment by markuman** [comment]
cc @goneri

**Comment by marknet15** [comment]
regate

**Comment by marknet15** [comment]
regate

**Pull request merged**
