### PR TITLE
Update extends_documentation_fragment with amazon.aws.boto3

### PR DESCRIPTION
**Pull request by alinabuzachis**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1654

##### SUMMARY

As per https://github.com/ansible-collections/amazon.aws/pull/985 add `amazon.aws.boto3`.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

several

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@tremble why does it still build cloudtrail docs? It cannot find cloudtrail because if has been moved to amazon.aws and that's the reason of the failure.

**Comment by tremble** [comment]
@alinabuzachis It's building a stub which redirects you over to `amazon.aws`.

For now we'll need to add a temporary stub similar to:
- https://github.com/ansible-collections/community.general/blob/main/.github/workflows/docs-pr.yml#L31

IMO the 'right' solution will be to tell the action about the new published docs over on github pages.  However, there's work that needs to go into this...

**Review by jillr — APPROVED** [review]

**Comment by alinabuzachis** [comment]
recheck

**Comment by goneri** [comment]
Some PR have been merged manually and this broken the consistency of the cache that `ansible-test-splitter` use.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
I'm working on a fix for the `ansible-test-splitter` failure.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
- Last failure was caused by https://github.com/ansible-collections/community.aws/pull/1477
- I've also updated https://github.com/ansible-collections/community.aws/pull/1467 to avoid the timeout.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
regate

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by tremble — APPROVED** [review]

**Review by markuman — APPROVED** [review]

**Pull request merged**
