### PR TITLE
fix assert of deploymentCircuitBreaker

### PR DESCRIPTION
**Pull request by markuman**
##### SUMMARY
fix broken ecs_cluster integration test of https://github.com/ansible-collections/community.aws/pull/1215

cc @tremble  @karcadia

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Review by tremble — APPROVED** [review]
Run tests locally and they now pass.  I'd missed that they didn't run last time.

**Comment by karcadia** [comment]
Wow woops thanks for cleaning this up!

Doesn't the PR pipeline run the integration tests? Was there a way for me to tell that it was failing?
Maybe I'll just run my tests offline before submitting next time.

**Comment by markuman** [comment]
> Doesn't the PR pipeline run the integration tests? 

ATM not. But work for it is [in progress](https://github.com/mattclay/aws-terminator/pull/210).

> Was there a way for me to tell that it was failing? Maybe I'll just run my tests offline before submitting next time.

basically you're place the `cloud-config-aws.ini.template` into your fork/clone and fill out the credentials

```
cp ~/.local/lib/python3.10/site-packages/ansible_test/config/cloud-config-aws.ini.template tests/integration/cloud-config-aws.ini
```

afterwards you can run 

```
ansible-test integration -v ecs_cluster --docker default --allow-unsupported
```

but somewhere must be also a more detailed manual for it.

**Pull request merged**
