### PR TITLE
[7.0.0] Apply isort and flynt

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Apply isort - see also  https://github.com/ansible-collections/amazon.aws/pull/1771
Apply flynt - see also https://github.com/ansible-collections/amazon.aws/pull/1802

##### ISSUE TYPE

- Feature Pull Request

### CODE REVIEW

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Comment by tremble** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by tremble** [comment]
retry

**Comment by tremble** [comment]
regate

**Comment by tremble** [comment]
Manual merge (touches github workflows)

**Pull request merged**
